# Drop-in replacements of internal-only libraries for open-source version.

package(
    default_visibility = ["//visibility:public"],
)

licenses(["notice"])  # Apache 2.0

py_library(
    name = "build_data",
    srcs = ["build_data.py"],
)

py_library(
    name = "error",
    srcs = ["error.py"],
)
