# Deepmath toplevel

package(
    default_visibility = ["//visibility:public"],
)

licenses(["notice"])  # Apache 2.0

exports_files(["LICENSE"])

filegroup(
    name = "all_files",
    data = [
        "//deepmath/hol:all_files",
        "//deepmath/holstep:all_files",
        "//deepmath/tools:all_files",
        "//deepmath/zz:all_files",
        "//deepmath/zz/CmdLine:all_files",
        "//deepmath/zz/Console:all_files",
        "//deepmath/zz/Generics:all_files",
        "//deepmath/zz/HolLight:all_files",
        "//deepmath/zz/Prelude:all_files",
    ],
)
