// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: synth.proto

#ifndef PROTOBUF_synth_2eproto__INCLUDED
#define PROTOBUF_synth_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace CodeBreeder {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_synth_2eproto();
void protobuf_AssignDesc_synth_2eproto();
void protobuf_ShutdownFile_synth_2eproto();

class TypeProto;
class NodeProto;
class StateProto;
class PoolProto;
class TrainingProto;

enum NodeKind {
  NIL = 0,
  POOL = 1,
  PI = 2,
  ID = 3,
  APPL = 4,
  TUPLE = 5,
  SEL = 6,
  LAMB = 7,
  OBL = 8,
  SCOPE = 9,
  BEGIN = 10,
  END = 11
};
bool NodeKind_IsValid(int value);
const NodeKind NodeKind_MIN = NIL;
const NodeKind NodeKind_MAX = END;
const int NodeKind_ARRAYSIZE = NodeKind_MAX + 1;

const ::google::protobuf::EnumDescriptor* NodeKind_descriptor();
inline const ::std::string& NodeKind_Name(NodeKind value) {
  return ::google::protobuf::internal::NameOfEnum(
    NodeKind_descriptor(), value);
}
inline bool NodeKind_Parse(
    const ::std::string& name, NodeKind* value) {
  return ::google::protobuf::internal::ParseNamedEnum<NodeKind>(
    NodeKind_descriptor(), name, value);
}
// ===================================================================

class TypeProto : public ::google::protobuf::Message {
 public:
  TypeProto();
  virtual ~TypeProto();

  TypeProto(const TypeProto& from);

  inline TypeProto& operator=(const TypeProto& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const TypeProto& default_instance();

  void Swap(TypeProto* other);

  // implements Message ----------------------------------------------

  TypeProto* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const TypeProto& from);
  void MergeFrom(const TypeProto& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string name = 1;
  inline bool has_name() const;
  inline void clear_name();
  static const int kNameFieldNumber = 1;
  inline const ::std::string& name() const;
  inline void set_name(const ::std::string& value);
  inline void set_name(const char* value);
  inline void set_name(const char* value, size_t size);
  inline ::std::string* mutable_name();
  inline ::std::string* release_name();
  inline void set_allocated_name(::std::string* name);

  // repeated .CodeBreeder.TypeProto arg = 2;
  inline int arg_size() const;
  inline void clear_arg();
  static const int kArgFieldNumber = 2;
  inline const ::CodeBreeder::TypeProto& arg(int index) const;
  inline ::CodeBreeder::TypeProto* mutable_arg(int index);
  inline ::CodeBreeder::TypeProto* add_arg();
  inline const ::google::protobuf::RepeatedPtrField< ::CodeBreeder::TypeProto >&
      arg() const;
  inline ::google::protobuf::RepeatedPtrField< ::CodeBreeder::TypeProto >*
      mutable_arg();

  // @@protoc_insertion_point(class_scope:CodeBreeder.TypeProto)
 private:
  inline void set_has_name();
  inline void clear_has_name();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::std::string* name_;
  ::google::protobuf::RepeatedPtrField< ::CodeBreeder::TypeProto > arg_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_synth_2eproto();
  friend void protobuf_AssignDesc_synth_2eproto();
  friend void protobuf_ShutdownFile_synth_2eproto();

  void InitAsDefaultInstance();
  static TypeProto* default_instance_;
};
// -------------------------------------------------------------------

class NodeProto : public ::google::protobuf::Message {
 public:
  NodeProto();
  virtual ~NodeProto();

  NodeProto(const NodeProto& from);

  inline NodeProto& operator=(const NodeProto& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const NodeProto& default_instance();

  void Swap(NodeProto* other);

  // implements Message ----------------------------------------------

  NodeProto* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const NodeProto& from);
  void MergeFrom(const NodeProto& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string kind = 1;
  inline bool has_kind() const;
  inline void clear_kind();
  static const int kKindFieldNumber = 1;
  inline const ::std::string& kind() const;
  inline void set_kind(const ::std::string& value);
  inline void set_kind(const char* value);
  inline void set_kind(const char* value, size_t size);
  inline ::std::string* mutable_kind();
  inline ::std::string* release_kind();
  inline void set_allocated_kind(::std::string* kind);

  // optional bool internal = 2;
  inline bool has_internal() const;
  inline void clear_internal();
  static const int kInternalFieldNumber = 2;
  inline bool internal() const;
  inline void set_internal(bool value);

  // optional double cost = 3;
  inline bool has_cost() const;
  inline void clear_cost();
  static const int kCostFieldNumber = 3;
  inline double cost() const;
  inline void set_cost(double value);

  // repeated int32 input = 4;
  inline int input_size() const;
  inline void clear_input();
  static const int kInputFieldNumber = 4;
  inline ::google::protobuf::int32 input(int index) const;
  inline void set_input(int index, ::google::protobuf::int32 value);
  inline void add_input(::google::protobuf::int32 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      input() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_input();

  // optional .CodeBreeder.TypeProto type_proto = 5;
  inline bool has_type_proto() const;
  inline void clear_type_proto();
  static const int kTypeProtoFieldNumber = 5;
  inline const ::CodeBreeder::TypeProto& type_proto() const;
  inline ::CodeBreeder::TypeProto* mutable_type_proto();
  inline ::CodeBreeder::TypeProto* release_type_proto();
  inline void set_allocated_type_proto(::CodeBreeder::TypeProto* type_proto);

  // @@protoc_insertion_point(class_scope:CodeBreeder.NodeProto)
 private:
  inline void set_has_kind();
  inline void clear_has_kind();
  inline void set_has_internal();
  inline void clear_has_internal();
  inline void set_has_cost();
  inline void clear_has_cost();
  inline void set_has_type_proto();
  inline void clear_has_type_proto();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::std::string* kind_;
  double cost_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > input_;
  ::CodeBreeder::TypeProto* type_proto_;
  bool internal_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(5 + 31) / 32];

  friend void  protobuf_AddDesc_synth_2eproto();
  friend void protobuf_AssignDesc_synth_2eproto();
  friend void protobuf_ShutdownFile_synth_2eproto();

  void InitAsDefaultInstance();
  static NodeProto* default_instance_;
};
// -------------------------------------------------------------------

class StateProto : public ::google::protobuf::Message {
 public:
  StateProto();
  virtual ~StateProto();

  StateProto(const StateProto& from);

  inline StateProto& operator=(const StateProto& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const StateProto& default_instance();

  void Swap(StateProto* other);

  // implements Message ----------------------------------------------

  StateProto* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const StateProto& from);
  void MergeFrom(const StateProto& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint64 state_id = 1;
  inline bool has_state_id() const;
  inline void clear_state_id();
  static const int kStateIdFieldNumber = 1;
  inline ::google::protobuf::uint64 state_id() const;
  inline void set_state_id(::google::protobuf::uint64 value);

  // repeated .CodeBreeder.NodeProto node = 2;
  inline int node_size() const;
  inline void clear_node();
  static const int kNodeFieldNumber = 2;
  inline const ::CodeBreeder::NodeProto& node(int index) const;
  inline ::CodeBreeder::NodeProto* mutable_node(int index);
  inline ::CodeBreeder::NodeProto* add_node();
  inline const ::google::protobuf::RepeatedPtrField< ::CodeBreeder::NodeProto >&
      node() const;
  inline ::google::protobuf::RepeatedPtrField< ::CodeBreeder::NodeProto >*
      mutable_node();

  // @@protoc_insertion_point(class_scope:CodeBreeder.StateProto)
 private:
  inline void set_has_state_id();
  inline void clear_has_state_id();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint64 state_id_;
  ::google::protobuf::RepeatedPtrField< ::CodeBreeder::NodeProto > node_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_synth_2eproto();
  friend void protobuf_AssignDesc_synth_2eproto();
  friend void protobuf_ShutdownFile_synth_2eproto();

  void InitAsDefaultInstance();
  static StateProto* default_instance_;
};
// -------------------------------------------------------------------

class PoolProto : public ::google::protobuf::Message {
 public:
  PoolProto();
  virtual ~PoolProto();

  PoolProto(const PoolProto& from);

  inline PoolProto& operator=(const PoolProto& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PoolProto& default_instance();

  void Swap(PoolProto* other);

  // implements Message ----------------------------------------------

  PoolProto* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const PoolProto& from);
  void MergeFrom(const PoolProto& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated string name = 1;
  inline int name_size() const;
  inline void clear_name();
  static const int kNameFieldNumber = 1;
  inline const ::std::string& name(int index) const;
  inline ::std::string* mutable_name(int index);
  inline void set_name(int index, const ::std::string& value);
  inline void set_name(int index, const char* value);
  inline void set_name(int index, const char* value, size_t size);
  inline ::std::string* add_name();
  inline void add_name(const ::std::string& value);
  inline void add_name(const char* value);
  inline void add_name(const char* value, size_t size);
  inline const ::google::protobuf::RepeatedPtrField< ::std::string>& name() const;
  inline ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_name();

  // repeated .CodeBreeder.TypeProto type_proto = 2;
  inline int type_proto_size() const;
  inline void clear_type_proto();
  static const int kTypeProtoFieldNumber = 2;
  inline const ::CodeBreeder::TypeProto& type_proto(int index) const;
  inline ::CodeBreeder::TypeProto* mutable_type_proto(int index);
  inline ::CodeBreeder::TypeProto* add_type_proto();
  inline const ::google::protobuf::RepeatedPtrField< ::CodeBreeder::TypeProto >&
      type_proto() const;
  inline ::google::protobuf::RepeatedPtrField< ::CodeBreeder::TypeProto >*
      mutable_type_proto();

  // repeated string qualified_name = 3;
  inline int qualified_name_size() const;
  inline void clear_qualified_name();
  static const int kQualifiedNameFieldNumber = 3;
  inline const ::std::string& qualified_name(int index) const;
  inline ::std::string* mutable_qualified_name(int index);
  inline void set_qualified_name(int index, const ::std::string& value);
  inline void set_qualified_name(int index, const char* value);
  inline void set_qualified_name(int index, const char* value, size_t size);
  inline ::std::string* add_qualified_name();
  inline void add_qualified_name(const ::std::string& value);
  inline void add_qualified_name(const char* value);
  inline void add_qualified_name(const char* value, size_t size);
  inline const ::google::protobuf::RepeatedPtrField< ::std::string>& qualified_name() const;
  inline ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_qualified_name();

  // @@protoc_insertion_point(class_scope:CodeBreeder.PoolProto)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::RepeatedPtrField< ::std::string> name_;
  ::google::protobuf::RepeatedPtrField< ::CodeBreeder::TypeProto > type_proto_;
  ::google::protobuf::RepeatedPtrField< ::std::string> qualified_name_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];

  friend void  protobuf_AddDesc_synth_2eproto();
  friend void protobuf_AssignDesc_synth_2eproto();
  friend void protobuf_ShutdownFile_synth_2eproto();

  void InitAsDefaultInstance();
  static PoolProto* default_instance_;
};
// -------------------------------------------------------------------

class TrainingProto : public ::google::protobuf::Message {
 public:
  TrainingProto();
  virtual ~TrainingProto();

  TrainingProto(const TrainingProto& from);

  inline TrainingProto& operator=(const TrainingProto& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const TrainingProto& default_instance();

  void Swap(TrainingProto* other);

  // implements Message ----------------------------------------------

  TrainingProto* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const TrainingProto& from);
  void MergeFrom(const TrainingProto& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .CodeBreeder.PoolProto pool_proto = 1;
  inline bool has_pool_proto() const;
  inline void clear_pool_proto();
  static const int kPoolProtoFieldNumber = 1;
  inline const ::CodeBreeder::PoolProto& pool_proto() const;
  inline ::CodeBreeder::PoolProto* mutable_pool_proto();
  inline ::CodeBreeder::PoolProto* release_pool_proto();
  inline void set_allocated_pool_proto(::CodeBreeder::PoolProto* pool_proto);

  // repeated .CodeBreeder.StateProto positive = 2;
  inline int positive_size() const;
  inline void clear_positive();
  static const int kPositiveFieldNumber = 2;
  inline const ::CodeBreeder::StateProto& positive(int index) const;
  inline ::CodeBreeder::StateProto* mutable_positive(int index);
  inline ::CodeBreeder::StateProto* add_positive();
  inline const ::google::protobuf::RepeatedPtrField< ::CodeBreeder::StateProto >&
      positive() const;
  inline ::google::protobuf::RepeatedPtrField< ::CodeBreeder::StateProto >*
      mutable_positive();

  // repeated .CodeBreeder.StateProto negative = 3;
  inline int negative_size() const;
  inline void clear_negative();
  static const int kNegativeFieldNumber = 3;
  inline const ::CodeBreeder::StateProto& negative(int index) const;
  inline ::CodeBreeder::StateProto* mutable_negative(int index);
  inline ::CodeBreeder::StateProto* add_negative();
  inline const ::google::protobuf::RepeatedPtrField< ::CodeBreeder::StateProto >&
      negative() const;
  inline ::google::protobuf::RepeatedPtrField< ::CodeBreeder::StateProto >*
      mutable_negative();

  // repeated bool property_features = 4;
  inline int property_features_size() const;
  inline void clear_property_features();
  static const int kPropertyFeaturesFieldNumber = 4;
  inline bool property_features(int index) const;
  inline void set_property_features(int index, bool value);
  inline void add_property_features(bool value);
  inline const ::google::protobuf::RepeatedField< bool >&
      property_features() const;
  inline ::google::protobuf::RepeatedField< bool >*
      mutable_property_features();

  // optional string evo_code = 5;
  inline bool has_evo_code() const;
  inline void clear_evo_code();
  static const int kEvoCodeFieldNumber = 5;
  inline const ::std::string& evo_code() const;
  inline void set_evo_code(const ::std::string& value);
  inline void set_evo_code(const char* value);
  inline void set_evo_code(const char* value, size_t size);
  inline ::std::string* mutable_evo_code();
  inline ::std::string* release_evo_code();
  inline void set_allocated_evo_code(::std::string* evo_code);

  // optional string evo_output = 6;
  inline bool has_evo_output() const;
  inline void clear_evo_output();
  static const int kEvoOutputFieldNumber = 6;
  inline const ::std::string& evo_output() const;
  inline void set_evo_output(const ::std::string& value);
  inline void set_evo_output(const char* value);
  inline void set_evo_output(const char* value, size_t size);
  inline ::std::string* mutable_evo_output();
  inline ::std::string* release_evo_output();
  inline void set_allocated_evo_output(::std::string* evo_output);

  // optional string type_string = 7;
  inline bool has_type_string() const;
  inline void clear_type_string();
  static const int kTypeStringFieldNumber = 7;
  inline const ::std::string& type_string() const;
  inline void set_type_string(const ::std::string& value);
  inline void set_type_string(const char* value);
  inline void set_type_string(const char* value, size_t size);
  inline ::std::string* mutable_type_string();
  inline ::std::string* release_type_string();
  inline void set_allocated_type_string(::std::string* type_string);

  // @@protoc_insertion_point(class_scope:CodeBreeder.TrainingProto)
 private:
  inline void set_has_pool_proto();
  inline void clear_has_pool_proto();
  inline void set_has_evo_code();
  inline void clear_has_evo_code();
  inline void set_has_evo_output();
  inline void clear_has_evo_output();
  inline void set_has_type_string();
  inline void clear_has_type_string();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::CodeBreeder::PoolProto* pool_proto_;
  ::google::protobuf::RepeatedPtrField< ::CodeBreeder::StateProto > positive_;
  ::google::protobuf::RepeatedPtrField< ::CodeBreeder::StateProto > negative_;
  ::google::protobuf::RepeatedField< bool > property_features_;
  ::std::string* evo_code_;
  ::std::string* evo_output_;
  ::std::string* type_string_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(7 + 31) / 32];

  friend void  protobuf_AddDesc_synth_2eproto();
  friend void protobuf_AssignDesc_synth_2eproto();
  friend void protobuf_ShutdownFile_synth_2eproto();

  void InitAsDefaultInstance();
  static TrainingProto* default_instance_;
};
// ===================================================================


// ===================================================================

// TypeProto

// optional string name = 1;
inline bool TypeProto::has_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void TypeProto::set_has_name() {
  _has_bits_[0] |= 0x00000001u;
}
inline void TypeProto::clear_has_name() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void TypeProto::clear_name() {
  if (name_ != &::google::protobuf::internal::kEmptyString) {
    name_->clear();
  }
  clear_has_name();
}
inline const ::std::string& TypeProto::name() const {
  return *name_;
}
inline void TypeProto::set_name(const ::std::string& value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(value);
}
inline void TypeProto::set_name(const char* value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(value);
}
inline void TypeProto::set_name(const char* value, size_t size) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* TypeProto::mutable_name() {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  return name_;
}
inline ::std::string* TypeProto::release_name() {
  clear_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = name_;
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void TypeProto::set_allocated_name(::std::string* name) {
  if (name_ != &::google::protobuf::internal::kEmptyString) {
    delete name_;
  }
  if (name) {
    set_has_name();
    name_ = name;
  } else {
    clear_has_name();
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// repeated .CodeBreeder.TypeProto arg = 2;
inline int TypeProto::arg_size() const {
  return arg_.size();
}
inline void TypeProto::clear_arg() {
  arg_.Clear();
}
inline const ::CodeBreeder::TypeProto& TypeProto::arg(int index) const {
  return arg_.Get(index);
}
inline ::CodeBreeder::TypeProto* TypeProto::mutable_arg(int index) {
  return arg_.Mutable(index);
}
inline ::CodeBreeder::TypeProto* TypeProto::add_arg() {
  return arg_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::CodeBreeder::TypeProto >&
TypeProto::arg() const {
  return arg_;
}
inline ::google::protobuf::RepeatedPtrField< ::CodeBreeder::TypeProto >*
TypeProto::mutable_arg() {
  return &arg_;
}

// -------------------------------------------------------------------

// NodeProto

// optional string kind = 1;
inline bool NodeProto::has_kind() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void NodeProto::set_has_kind() {
  _has_bits_[0] |= 0x00000001u;
}
inline void NodeProto::clear_has_kind() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void NodeProto::clear_kind() {
  if (kind_ != &::google::protobuf::internal::kEmptyString) {
    kind_->clear();
  }
  clear_has_kind();
}
inline const ::std::string& NodeProto::kind() const {
  return *kind_;
}
inline void NodeProto::set_kind(const ::std::string& value) {
  set_has_kind();
  if (kind_ == &::google::protobuf::internal::kEmptyString) {
    kind_ = new ::std::string;
  }
  kind_->assign(value);
}
inline void NodeProto::set_kind(const char* value) {
  set_has_kind();
  if (kind_ == &::google::protobuf::internal::kEmptyString) {
    kind_ = new ::std::string;
  }
  kind_->assign(value);
}
inline void NodeProto::set_kind(const char* value, size_t size) {
  set_has_kind();
  if (kind_ == &::google::protobuf::internal::kEmptyString) {
    kind_ = new ::std::string;
  }
  kind_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* NodeProto::mutable_kind() {
  set_has_kind();
  if (kind_ == &::google::protobuf::internal::kEmptyString) {
    kind_ = new ::std::string;
  }
  return kind_;
}
inline ::std::string* NodeProto::release_kind() {
  clear_has_kind();
  if (kind_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = kind_;
    kind_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void NodeProto::set_allocated_kind(::std::string* kind) {
  if (kind_ != &::google::protobuf::internal::kEmptyString) {
    delete kind_;
  }
  if (kind) {
    set_has_kind();
    kind_ = kind;
  } else {
    clear_has_kind();
    kind_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// optional bool internal = 2;
inline bool NodeProto::has_internal() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void NodeProto::set_has_internal() {
  _has_bits_[0] |= 0x00000002u;
}
inline void NodeProto::clear_has_internal() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void NodeProto::clear_internal() {
  internal_ = false;
  clear_has_internal();
}
inline bool NodeProto::internal() const {
  return internal_;
}
inline void NodeProto::set_internal(bool value) {
  set_has_internal();
  internal_ = value;
}

// optional double cost = 3;
inline bool NodeProto::has_cost() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void NodeProto::set_has_cost() {
  _has_bits_[0] |= 0x00000004u;
}
inline void NodeProto::clear_has_cost() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void NodeProto::clear_cost() {
  cost_ = 0;
  clear_has_cost();
}
inline double NodeProto::cost() const {
  return cost_;
}
inline void NodeProto::set_cost(double value) {
  set_has_cost();
  cost_ = value;
}

// repeated int32 input = 4;
inline int NodeProto::input_size() const {
  return input_.size();
}
inline void NodeProto::clear_input() {
  input_.Clear();
}
inline ::google::protobuf::int32 NodeProto::input(int index) const {
  return input_.Get(index);
}
inline void NodeProto::set_input(int index, ::google::protobuf::int32 value) {
  input_.Set(index, value);
}
inline void NodeProto::add_input(::google::protobuf::int32 value) {
  input_.Add(value);
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
NodeProto::input() const {
  return input_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
NodeProto::mutable_input() {
  return &input_;
}

// optional .CodeBreeder.TypeProto type_proto = 5;
inline bool NodeProto::has_type_proto() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void NodeProto::set_has_type_proto() {
  _has_bits_[0] |= 0x00000010u;
}
inline void NodeProto::clear_has_type_proto() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void NodeProto::clear_type_proto() {
  if (type_proto_ != NULL) type_proto_->::CodeBreeder::TypeProto::Clear();
  clear_has_type_proto();
}
inline const ::CodeBreeder::TypeProto& NodeProto::type_proto() const {
  return type_proto_ != NULL ? *type_proto_ : *default_instance_->type_proto_;
}
inline ::CodeBreeder::TypeProto* NodeProto::mutable_type_proto() {
  set_has_type_proto();
  if (type_proto_ == NULL) type_proto_ = new ::CodeBreeder::TypeProto;
  return type_proto_;
}
inline ::CodeBreeder::TypeProto* NodeProto::release_type_proto() {
  clear_has_type_proto();
  ::CodeBreeder::TypeProto* temp = type_proto_;
  type_proto_ = NULL;
  return temp;
}
inline void NodeProto::set_allocated_type_proto(::CodeBreeder::TypeProto* type_proto) {
  delete type_proto_;
  type_proto_ = type_proto;
  if (type_proto) {
    set_has_type_proto();
  } else {
    clear_has_type_proto();
  }
}

// -------------------------------------------------------------------

// StateProto

// required uint64 state_id = 1;
inline bool StateProto::has_state_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void StateProto::set_has_state_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void StateProto::clear_has_state_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void StateProto::clear_state_id() {
  state_id_ = GOOGLE_ULONGLONG(0);
  clear_has_state_id();
}
inline ::google::protobuf::uint64 StateProto::state_id() const {
  return state_id_;
}
inline void StateProto::set_state_id(::google::protobuf::uint64 value) {
  set_has_state_id();
  state_id_ = value;
}

// repeated .CodeBreeder.NodeProto node = 2;
inline int StateProto::node_size() const {
  return node_.size();
}
inline void StateProto::clear_node() {
  node_.Clear();
}
inline const ::CodeBreeder::NodeProto& StateProto::node(int index) const {
  return node_.Get(index);
}
inline ::CodeBreeder::NodeProto* StateProto::mutable_node(int index) {
  return node_.Mutable(index);
}
inline ::CodeBreeder::NodeProto* StateProto::add_node() {
  return node_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::CodeBreeder::NodeProto >&
StateProto::node() const {
  return node_;
}
inline ::google::protobuf::RepeatedPtrField< ::CodeBreeder::NodeProto >*
StateProto::mutable_node() {
  return &node_;
}

// -------------------------------------------------------------------

// PoolProto

// repeated string name = 1;
inline int PoolProto::name_size() const {
  return name_.size();
}
inline void PoolProto::clear_name() {
  name_.Clear();
}
inline const ::std::string& PoolProto::name(int index) const {
  return name_.Get(index);
}
inline ::std::string* PoolProto::mutable_name(int index) {
  return name_.Mutable(index);
}
inline void PoolProto::set_name(int index, const ::std::string& value) {
  name_.Mutable(index)->assign(value);
}
inline void PoolProto::set_name(int index, const char* value) {
  name_.Mutable(index)->assign(value);
}
inline void PoolProto::set_name(int index, const char* value, size_t size) {
  name_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
}
inline ::std::string* PoolProto::add_name() {
  return name_.Add();
}
inline void PoolProto::add_name(const ::std::string& value) {
  name_.Add()->assign(value);
}
inline void PoolProto::add_name(const char* value) {
  name_.Add()->assign(value);
}
inline void PoolProto::add_name(const char* value, size_t size) {
  name_.Add()->assign(reinterpret_cast<const char*>(value), size);
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
PoolProto::name() const {
  return name_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
PoolProto::mutable_name() {
  return &name_;
}

// repeated .CodeBreeder.TypeProto type_proto = 2;
inline int PoolProto::type_proto_size() const {
  return type_proto_.size();
}
inline void PoolProto::clear_type_proto() {
  type_proto_.Clear();
}
inline const ::CodeBreeder::TypeProto& PoolProto::type_proto(int index) const {
  return type_proto_.Get(index);
}
inline ::CodeBreeder::TypeProto* PoolProto::mutable_type_proto(int index) {
  return type_proto_.Mutable(index);
}
inline ::CodeBreeder::TypeProto* PoolProto::add_type_proto() {
  return type_proto_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::CodeBreeder::TypeProto >&
PoolProto::type_proto() const {
  return type_proto_;
}
inline ::google::protobuf::RepeatedPtrField< ::CodeBreeder::TypeProto >*
PoolProto::mutable_type_proto() {
  return &type_proto_;
}

// repeated string qualified_name = 3;
inline int PoolProto::qualified_name_size() const {
  return qualified_name_.size();
}
inline void PoolProto::clear_qualified_name() {
  qualified_name_.Clear();
}
inline const ::std::string& PoolProto::qualified_name(int index) const {
  return qualified_name_.Get(index);
}
inline ::std::string* PoolProto::mutable_qualified_name(int index) {
  return qualified_name_.Mutable(index);
}
inline void PoolProto::set_qualified_name(int index, const ::std::string& value) {
  qualified_name_.Mutable(index)->assign(value);
}
inline void PoolProto::set_qualified_name(int index, const char* value) {
  qualified_name_.Mutable(index)->assign(value);
}
inline void PoolProto::set_qualified_name(int index, const char* value, size_t size) {
  qualified_name_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
}
inline ::std::string* PoolProto::add_qualified_name() {
  return qualified_name_.Add();
}
inline void PoolProto::add_qualified_name(const ::std::string& value) {
  qualified_name_.Add()->assign(value);
}
inline void PoolProto::add_qualified_name(const char* value) {
  qualified_name_.Add()->assign(value);
}
inline void PoolProto::add_qualified_name(const char* value, size_t size) {
  qualified_name_.Add()->assign(reinterpret_cast<const char*>(value), size);
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
PoolProto::qualified_name() const {
  return qualified_name_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
PoolProto::mutable_qualified_name() {
  return &qualified_name_;
}

// -------------------------------------------------------------------

// TrainingProto

// optional .CodeBreeder.PoolProto pool_proto = 1;
inline bool TrainingProto::has_pool_proto() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void TrainingProto::set_has_pool_proto() {
  _has_bits_[0] |= 0x00000001u;
}
inline void TrainingProto::clear_has_pool_proto() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void TrainingProto::clear_pool_proto() {
  if (pool_proto_ != NULL) pool_proto_->::CodeBreeder::PoolProto::Clear();
  clear_has_pool_proto();
}
inline const ::CodeBreeder::PoolProto& TrainingProto::pool_proto() const {
  return pool_proto_ != NULL ? *pool_proto_ : *default_instance_->pool_proto_;
}
inline ::CodeBreeder::PoolProto* TrainingProto::mutable_pool_proto() {
  set_has_pool_proto();
  if (pool_proto_ == NULL) pool_proto_ = new ::CodeBreeder::PoolProto;
  return pool_proto_;
}
inline ::CodeBreeder::PoolProto* TrainingProto::release_pool_proto() {
  clear_has_pool_proto();
  ::CodeBreeder::PoolProto* temp = pool_proto_;
  pool_proto_ = NULL;
  return temp;
}
inline void TrainingProto::set_allocated_pool_proto(::CodeBreeder::PoolProto* pool_proto) {
  delete pool_proto_;
  pool_proto_ = pool_proto;
  if (pool_proto) {
    set_has_pool_proto();
  } else {
    clear_has_pool_proto();
  }
}

// repeated .CodeBreeder.StateProto positive = 2;
inline int TrainingProto::positive_size() const {
  return positive_.size();
}
inline void TrainingProto::clear_positive() {
  positive_.Clear();
}
inline const ::CodeBreeder::StateProto& TrainingProto::positive(int index) const {
  return positive_.Get(index);
}
inline ::CodeBreeder::StateProto* TrainingProto::mutable_positive(int index) {
  return positive_.Mutable(index);
}
inline ::CodeBreeder::StateProto* TrainingProto::add_positive() {
  return positive_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::CodeBreeder::StateProto >&
TrainingProto::positive() const {
  return positive_;
}
inline ::google::protobuf::RepeatedPtrField< ::CodeBreeder::StateProto >*
TrainingProto::mutable_positive() {
  return &positive_;
}

// repeated .CodeBreeder.StateProto negative = 3;
inline int TrainingProto::negative_size() const {
  return negative_.size();
}
inline void TrainingProto::clear_negative() {
  negative_.Clear();
}
inline const ::CodeBreeder::StateProto& TrainingProto::negative(int index) const {
  return negative_.Get(index);
}
inline ::CodeBreeder::StateProto* TrainingProto::mutable_negative(int index) {
  return negative_.Mutable(index);
}
inline ::CodeBreeder::StateProto* TrainingProto::add_negative() {
  return negative_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::CodeBreeder::StateProto >&
TrainingProto::negative() const {
  return negative_;
}
inline ::google::protobuf::RepeatedPtrField< ::CodeBreeder::StateProto >*
TrainingProto::mutable_negative() {
  return &negative_;
}

// repeated bool property_features = 4;
inline int TrainingProto::property_features_size() const {
  return property_features_.size();
}
inline void TrainingProto::clear_property_features() {
  property_features_.Clear();
}
inline bool TrainingProto::property_features(int index) const {
  return property_features_.Get(index);
}
inline void TrainingProto::set_property_features(int index, bool value) {
  property_features_.Set(index, value);
}
inline void TrainingProto::add_property_features(bool value) {
  property_features_.Add(value);
}
inline const ::google::protobuf::RepeatedField< bool >&
TrainingProto::property_features() const {
  return property_features_;
}
inline ::google::protobuf::RepeatedField< bool >*
TrainingProto::mutable_property_features() {
  return &property_features_;
}

// optional string evo_code = 5;
inline bool TrainingProto::has_evo_code() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void TrainingProto::set_has_evo_code() {
  _has_bits_[0] |= 0x00000010u;
}
inline void TrainingProto::clear_has_evo_code() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void TrainingProto::clear_evo_code() {
  if (evo_code_ != &::google::protobuf::internal::kEmptyString) {
    evo_code_->clear();
  }
  clear_has_evo_code();
}
inline const ::std::string& TrainingProto::evo_code() const {
  return *evo_code_;
}
inline void TrainingProto::set_evo_code(const ::std::string& value) {
  set_has_evo_code();
  if (evo_code_ == &::google::protobuf::internal::kEmptyString) {
    evo_code_ = new ::std::string;
  }
  evo_code_->assign(value);
}
inline void TrainingProto::set_evo_code(const char* value) {
  set_has_evo_code();
  if (evo_code_ == &::google::protobuf::internal::kEmptyString) {
    evo_code_ = new ::std::string;
  }
  evo_code_->assign(value);
}
inline void TrainingProto::set_evo_code(const char* value, size_t size) {
  set_has_evo_code();
  if (evo_code_ == &::google::protobuf::internal::kEmptyString) {
    evo_code_ = new ::std::string;
  }
  evo_code_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* TrainingProto::mutable_evo_code() {
  set_has_evo_code();
  if (evo_code_ == &::google::protobuf::internal::kEmptyString) {
    evo_code_ = new ::std::string;
  }
  return evo_code_;
}
inline ::std::string* TrainingProto::release_evo_code() {
  clear_has_evo_code();
  if (evo_code_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = evo_code_;
    evo_code_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void TrainingProto::set_allocated_evo_code(::std::string* evo_code) {
  if (evo_code_ != &::google::protobuf::internal::kEmptyString) {
    delete evo_code_;
  }
  if (evo_code) {
    set_has_evo_code();
    evo_code_ = evo_code;
  } else {
    clear_has_evo_code();
    evo_code_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// optional string evo_output = 6;
inline bool TrainingProto::has_evo_output() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void TrainingProto::set_has_evo_output() {
  _has_bits_[0] |= 0x00000020u;
}
inline void TrainingProto::clear_has_evo_output() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void TrainingProto::clear_evo_output() {
  if (evo_output_ != &::google::protobuf::internal::kEmptyString) {
    evo_output_->clear();
  }
  clear_has_evo_output();
}
inline const ::std::string& TrainingProto::evo_output() const {
  return *evo_output_;
}
inline void TrainingProto::set_evo_output(const ::std::string& value) {
  set_has_evo_output();
  if (evo_output_ == &::google::protobuf::internal::kEmptyString) {
    evo_output_ = new ::std::string;
  }
  evo_output_->assign(value);
}
inline void TrainingProto::set_evo_output(const char* value) {
  set_has_evo_output();
  if (evo_output_ == &::google::protobuf::internal::kEmptyString) {
    evo_output_ = new ::std::string;
  }
  evo_output_->assign(value);
}
inline void TrainingProto::set_evo_output(const char* value, size_t size) {
  set_has_evo_output();
  if (evo_output_ == &::google::protobuf::internal::kEmptyString) {
    evo_output_ = new ::std::string;
  }
  evo_output_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* TrainingProto::mutable_evo_output() {
  set_has_evo_output();
  if (evo_output_ == &::google::protobuf::internal::kEmptyString) {
    evo_output_ = new ::std::string;
  }
  return evo_output_;
}
inline ::std::string* TrainingProto::release_evo_output() {
  clear_has_evo_output();
  if (evo_output_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = evo_output_;
    evo_output_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void TrainingProto::set_allocated_evo_output(::std::string* evo_output) {
  if (evo_output_ != &::google::protobuf::internal::kEmptyString) {
    delete evo_output_;
  }
  if (evo_output) {
    set_has_evo_output();
    evo_output_ = evo_output;
  } else {
    clear_has_evo_output();
    evo_output_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// optional string type_string = 7;
inline bool TrainingProto::has_type_string() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void TrainingProto::set_has_type_string() {
  _has_bits_[0] |= 0x00000040u;
}
inline void TrainingProto::clear_has_type_string() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void TrainingProto::clear_type_string() {
  if (type_string_ != &::google::protobuf::internal::kEmptyString) {
    type_string_->clear();
  }
  clear_has_type_string();
}
inline const ::std::string& TrainingProto::type_string() const {
  return *type_string_;
}
inline void TrainingProto::set_type_string(const ::std::string& value) {
  set_has_type_string();
  if (type_string_ == &::google::protobuf::internal::kEmptyString) {
    type_string_ = new ::std::string;
  }
  type_string_->assign(value);
}
inline void TrainingProto::set_type_string(const char* value) {
  set_has_type_string();
  if (type_string_ == &::google::protobuf::internal::kEmptyString) {
    type_string_ = new ::std::string;
  }
  type_string_->assign(value);
}
inline void TrainingProto::set_type_string(const char* value, size_t size) {
  set_has_type_string();
  if (type_string_ == &::google::protobuf::internal::kEmptyString) {
    type_string_ = new ::std::string;
  }
  type_string_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* TrainingProto::mutable_type_string() {
  set_has_type_string();
  if (type_string_ == &::google::protobuf::internal::kEmptyString) {
    type_string_ = new ::std::string;
  }
  return type_string_;
}
inline ::std::string* TrainingProto::release_type_string() {
  clear_has_type_string();
  if (type_string_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = type_string_;
    type_string_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void TrainingProto::set_allocated_type_string(::std::string* type_string) {
  if (type_string_ != &::google::protobuf::internal::kEmptyString) {
    delete type_string_;
  }
  if (type_string) {
    set_has_type_string();
    type_string_ = type_string;
  } else {
    clear_has_type_string();
    type_string_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace CodeBreeder

#ifndef SWIG
namespace google {
namespace protobuf {

template <>
inline const EnumDescriptor* GetEnumDescriptor< ::CodeBreeder::NodeKind>() {
  return ::CodeBreeder::NodeKind_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_synth_2eproto__INCLUDED
