// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: synth.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "synth.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace CodeBreeder {

namespace {

const ::google::protobuf::Descriptor* TypeProto_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  TypeProto_reflection_ = NULL;
const ::google::protobuf::Descriptor* NodeProto_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  NodeProto_reflection_ = NULL;
const ::google::protobuf::Descriptor* StateProto_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  StateProto_reflection_ = NULL;
const ::google::protobuf::Descriptor* PoolProto_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  PoolProto_reflection_ = NULL;
const ::google::protobuf::Descriptor* TrainingProto_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  TrainingProto_reflection_ = NULL;
const ::google::protobuf::EnumDescriptor* NodeKind_descriptor_ = NULL;

}  // namespace


void protobuf_AssignDesc_synth_2eproto() {
  protobuf_AddDesc_synth_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "synth.proto");
  GOOGLE_CHECK(file != NULL);
  TypeProto_descriptor_ = file->message_type(0);
  static const int TypeProto_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TypeProto, name_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TypeProto, arg_),
  };
  TypeProto_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      TypeProto_descriptor_,
      TypeProto::default_instance_,
      TypeProto_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TypeProto, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TypeProto, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(TypeProto));
  NodeProto_descriptor_ = file->message_type(1);
  static const int NodeProto_offsets_[5] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(NodeProto, kind_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(NodeProto, internal_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(NodeProto, cost_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(NodeProto, input_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(NodeProto, type_proto_),
  };
  NodeProto_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      NodeProto_descriptor_,
      NodeProto::default_instance_,
      NodeProto_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(NodeProto, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(NodeProto, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(NodeProto));
  StateProto_descriptor_ = file->message_type(2);
  static const int StateProto_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(StateProto, state_id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(StateProto, node_),
  };
  StateProto_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      StateProto_descriptor_,
      StateProto::default_instance_,
      StateProto_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(StateProto, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(StateProto, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(StateProto));
  PoolProto_descriptor_ = file->message_type(3);
  static const int PoolProto_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PoolProto, name_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PoolProto, type_proto_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PoolProto, qualified_name_),
  };
  PoolProto_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      PoolProto_descriptor_,
      PoolProto::default_instance_,
      PoolProto_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PoolProto, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PoolProto, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(PoolProto));
  TrainingProto_descriptor_ = file->message_type(4);
  static const int TrainingProto_offsets_[7] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TrainingProto, pool_proto_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TrainingProto, positive_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TrainingProto, negative_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TrainingProto, property_features_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TrainingProto, evo_code_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TrainingProto, evo_output_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TrainingProto, type_string_),
  };
  TrainingProto_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      TrainingProto_descriptor_,
      TrainingProto::default_instance_,
      TrainingProto_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TrainingProto, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TrainingProto, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(TrainingProto));
  NodeKind_descriptor_ = file->enum_type(0);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_synth_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    TypeProto_descriptor_, &TypeProto::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    NodeProto_descriptor_, &NodeProto::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    StateProto_descriptor_, &StateProto::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    PoolProto_descriptor_, &PoolProto::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    TrainingProto_descriptor_, &TrainingProto::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_synth_2eproto() {
  delete TypeProto::default_instance_;
  delete TypeProto_reflection_;
  delete NodeProto::default_instance_;
  delete NodeProto_reflection_;
  delete StateProto::default_instance_;
  delete StateProto_reflection_;
  delete PoolProto::default_instance_;
  delete PoolProto_reflection_;
  delete TrainingProto::default_instance_;
  delete TrainingProto_reflection_;
}

void protobuf_AddDesc_synth_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\013synth.proto\022\013CodeBreeder\">\n\tTypeProto\022"
    "\014\n\004name\030\001 \001(\t\022#\n\003arg\030\002 \003(\0132\026.CodeBreeder"
    ".TypeProto\"t\n\tNodeProto\022\014\n\004kind\030\001 \001(\t\022\020\n"
    "\010internal\030\002 \001(\010\022\014\n\004cost\030\003 \001(\001\022\r\n\005input\030\004"
    " \003(\005\022*\n\ntype_proto\030\005 \001(\0132\026.CodeBreeder.T"
    "ypeProto\"D\n\nStateProto\022\020\n\010state_id\030\001 \002(\004"
    "\022$\n\004node\030\002 \003(\0132\026.CodeBreeder.NodeProto\"]"
    "\n\tPoolProto\022\014\n\004name\030\001 \003(\t\022*\n\ntype_proto\030"
    "\002 \003(\0132\026.CodeBreeder.TypeProto\022\026\n\016qualifi"
    "ed_name\030\003 \003(\t\"\347\001\n\rTrainingProto\022*\n\npool_"
    "proto\030\001 \001(\0132\026.CodeBreeder.PoolProto\022)\n\010p"
    "ositive\030\002 \003(\0132\027.CodeBreeder.StateProto\022)"
    "\n\010negative\030\003 \003(\0132\027.CodeBreeder.StateProt"
    "o\022\031\n\021property_features\030\004 \003(\010\022\020\n\010evo_code"
    "\030\005 \001(\t\022\022\n\nevo_output\030\006 \001(\t\022\023\n\013type_strin"
    "g\030\007 \001(\t*}\n\010NodeKind\022\007\n\003NIL\020\000\022\010\n\004POOL\020\001\022\006"
    "\n\002PI\020\002\022\006\n\002ID\020\003\022\010\n\004APPL\020\004\022\t\n\005TUPLE\020\005\022\007\n\003S"
    "EL\020\006\022\010\n\004LAMB\020\007\022\007\n\003OBL\020\010\022\t\n\005SCOPE\020\t\022\t\n\005BE"
    "GIN\020\n\022\007\n\003END\020\013", 734);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "synth.proto", &protobuf_RegisterTypes);
  TypeProto::default_instance_ = new TypeProto();
  NodeProto::default_instance_ = new NodeProto();
  StateProto::default_instance_ = new StateProto();
  PoolProto::default_instance_ = new PoolProto();
  TrainingProto::default_instance_ = new TrainingProto();
  TypeProto::default_instance_->InitAsDefaultInstance();
  NodeProto::default_instance_->InitAsDefaultInstance();
  StateProto::default_instance_->InitAsDefaultInstance();
  PoolProto::default_instance_->InitAsDefaultInstance();
  TrainingProto::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_synth_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_synth_2eproto {
  StaticDescriptorInitializer_synth_2eproto() {
    protobuf_AddDesc_synth_2eproto();
  }
} static_descriptor_initializer_synth_2eproto_;
const ::google::protobuf::EnumDescriptor* NodeKind_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return NodeKind_descriptor_;
}
bool NodeKind_IsValid(int value) {
  switch(value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
    case 8:
    case 9:
    case 10:
    case 11:
      return true;
    default:
      return false;
  }
}


// ===================================================================

#ifndef _MSC_VER
const int TypeProto::kNameFieldNumber;
const int TypeProto::kArgFieldNumber;
#endif  // !_MSC_VER

TypeProto::TypeProto()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void TypeProto::InitAsDefaultInstance() {
}

TypeProto::TypeProto(const TypeProto& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void TypeProto::SharedCtor() {
  _cached_size_ = 0;
  name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

TypeProto::~TypeProto() {
  SharedDtor();
}

void TypeProto::SharedDtor() {
  if (name_ != &::google::protobuf::internal::kEmptyString) {
    delete name_;
  }
  if (this != default_instance_) {
  }
}

void TypeProto::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* TypeProto::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return TypeProto_descriptor_;
}

const TypeProto& TypeProto::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_synth_2eproto();
  return *default_instance_;
}

TypeProto* TypeProto::default_instance_ = NULL;

TypeProto* TypeProto::New() const {
  return new TypeProto;
}

void TypeProto::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (has_name()) {
      if (name_ != &::google::protobuf::internal::kEmptyString) {
        name_->clear();
      }
    }
  }
  arg_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool TypeProto::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional string name = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_name()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->name().data(), this->name().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_arg;
        break;
      }

      // repeated .CodeBreeder.TypeProto arg = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_arg:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_arg()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_arg;
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void TypeProto::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // optional string name = 1;
  if (has_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->name().data(), this->name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      1, this->name(), output);
  }

  // repeated .CodeBreeder.TypeProto arg = 2;
  for (int i = 0; i < this->arg_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->arg(i), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* TypeProto::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // optional string name = 1;
  if (has_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->name().data(), this->name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->name(), target);
  }

  // repeated .CodeBreeder.TypeProto arg = 2;
  for (int i = 0; i < this->arg_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        2, this->arg(i), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int TypeProto::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional string name = 1;
    if (has_name()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->name());
    }

  }
  // repeated .CodeBreeder.TypeProto arg = 2;
  total_size += 1 * this->arg_size();
  for (int i = 0; i < this->arg_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->arg(i));
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void TypeProto::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const TypeProto* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const TypeProto*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void TypeProto::MergeFrom(const TypeProto& from) {
  GOOGLE_CHECK_NE(&from, this);
  arg_.MergeFrom(from.arg_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_name()) {
      set_name(from.name());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void TypeProto::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void TypeProto::CopyFrom(const TypeProto& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TypeProto::IsInitialized() const {

  return true;
}

void TypeProto::Swap(TypeProto* other) {
  if (other != this) {
    std::swap(name_, other->name_);
    arg_.Swap(&other->arg_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata TypeProto::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = TypeProto_descriptor_;
  metadata.reflection = TypeProto_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int NodeProto::kKindFieldNumber;
const int NodeProto::kInternalFieldNumber;
const int NodeProto::kCostFieldNumber;
const int NodeProto::kInputFieldNumber;
const int NodeProto::kTypeProtoFieldNumber;
#endif  // !_MSC_VER

NodeProto::NodeProto()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void NodeProto::InitAsDefaultInstance() {
  type_proto_ = const_cast< ::CodeBreeder::TypeProto*>(&::CodeBreeder::TypeProto::default_instance());
}

NodeProto::NodeProto(const NodeProto& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void NodeProto::SharedCtor() {
  _cached_size_ = 0;
  kind_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  internal_ = false;
  cost_ = 0;
  type_proto_ = NULL;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

NodeProto::~NodeProto() {
  SharedDtor();
}

void NodeProto::SharedDtor() {
  if (kind_ != &::google::protobuf::internal::kEmptyString) {
    delete kind_;
  }
  if (this != default_instance_) {
    delete type_proto_;
  }
}

void NodeProto::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* NodeProto::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return NodeProto_descriptor_;
}

const NodeProto& NodeProto::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_synth_2eproto();
  return *default_instance_;
}

NodeProto* NodeProto::default_instance_ = NULL;

NodeProto* NodeProto::New() const {
  return new NodeProto;
}

void NodeProto::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (has_kind()) {
      if (kind_ != &::google::protobuf::internal::kEmptyString) {
        kind_->clear();
      }
    }
    internal_ = false;
    cost_ = 0;
    if (has_type_proto()) {
      if (type_proto_ != NULL) type_proto_->::CodeBreeder::TypeProto::Clear();
    }
  }
  input_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool NodeProto::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional string kind = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_kind()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->kind().data(), this->kind().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_internal;
        break;
      }

      // optional bool internal = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_internal:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &internal_)));
          set_has_internal();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(25)) goto parse_cost;
        break;
      }

      // optional double cost = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED64) {
         parse_cost:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &cost_)));
          set_has_cost();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(32)) goto parse_input;
        break;
      }

      // repeated int32 input = 4;
      case 4: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_input:
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 1, 32, input, this->mutable_input())));
        } else if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag)
                   == ::google::protobuf::internal::WireFormatLite::
                      WIRETYPE_LENGTH_DELIMITED) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitiveNoInline<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, this->mutable_input())));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(32)) goto parse_input;
        if (input->ExpectTag(42)) goto parse_type_proto;
        break;
      }

      // optional .CodeBreeder.TypeProto type_proto = 5;
      case 5: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_type_proto:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_type_proto()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void NodeProto::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // optional string kind = 1;
  if (has_kind()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->kind().data(), this->kind().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      1, this->kind(), output);
  }

  // optional bool internal = 2;
  if (has_internal()) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(2, this->internal(), output);
  }

  // optional double cost = 3;
  if (has_cost()) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(3, this->cost(), output);
  }

  // repeated int32 input = 4;
  for (int i = 0; i < this->input_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(
      4, this->input(i), output);
  }

  // optional .CodeBreeder.TypeProto type_proto = 5;
  if (has_type_proto()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      5, this->type_proto(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* NodeProto::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // optional string kind = 1;
  if (has_kind()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->kind().data(), this->kind().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->kind(), target);
  }

  // optional bool internal = 2;
  if (has_internal()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(2, this->internal(), target);
  }

  // optional double cost = 3;
  if (has_cost()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(3, this->cost(), target);
  }

  // repeated int32 input = 4;
  for (int i = 0; i < this->input_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteInt32ToArray(4, this->input(i), target);
  }

  // optional .CodeBreeder.TypeProto type_proto = 5;
  if (has_type_proto()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        5, this->type_proto(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int NodeProto::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional string kind = 1;
    if (has_kind()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->kind());
    }

    // optional bool internal = 2;
    if (has_internal()) {
      total_size += 1 + 1;
    }

    // optional double cost = 3;
    if (has_cost()) {
      total_size += 1 + 8;
    }

    // optional .CodeBreeder.TypeProto type_proto = 5;
    if (has_type_proto()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->type_proto());
    }

  }
  // repeated int32 input = 4;
  {
    int data_size = 0;
    for (int i = 0; i < this->input_size(); i++) {
      data_size += ::google::protobuf::internal::WireFormatLite::
        Int32Size(this->input(i));
    }
    total_size += 1 * this->input_size() + data_size;
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void NodeProto::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const NodeProto* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const NodeProto*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void NodeProto::MergeFrom(const NodeProto& from) {
  GOOGLE_CHECK_NE(&from, this);
  input_.MergeFrom(from.input_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_kind()) {
      set_kind(from.kind());
    }
    if (from.has_internal()) {
      set_internal(from.internal());
    }
    if (from.has_cost()) {
      set_cost(from.cost());
    }
    if (from.has_type_proto()) {
      mutable_type_proto()->::CodeBreeder::TypeProto::MergeFrom(from.type_proto());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void NodeProto::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void NodeProto::CopyFrom(const NodeProto& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool NodeProto::IsInitialized() const {

  return true;
}

void NodeProto::Swap(NodeProto* other) {
  if (other != this) {
    std::swap(kind_, other->kind_);
    std::swap(internal_, other->internal_);
    std::swap(cost_, other->cost_);
    input_.Swap(&other->input_);
    std::swap(type_proto_, other->type_proto_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata NodeProto::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = NodeProto_descriptor_;
  metadata.reflection = NodeProto_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int StateProto::kStateIdFieldNumber;
const int StateProto::kNodeFieldNumber;
#endif  // !_MSC_VER

StateProto::StateProto()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void StateProto::InitAsDefaultInstance() {
}

StateProto::StateProto(const StateProto& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void StateProto::SharedCtor() {
  _cached_size_ = 0;
  state_id_ = GOOGLE_ULONGLONG(0);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

StateProto::~StateProto() {
  SharedDtor();
}

void StateProto::SharedDtor() {
  if (this != default_instance_) {
  }
}

void StateProto::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* StateProto::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return StateProto_descriptor_;
}

const StateProto& StateProto::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_synth_2eproto();
  return *default_instance_;
}

StateProto* StateProto::default_instance_ = NULL;

StateProto* StateProto::New() const {
  return new StateProto;
}

void StateProto::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    state_id_ = GOOGLE_ULONGLONG(0);
  }
  node_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool StateProto::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required uint64 state_id = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &state_id_)));
          set_has_state_id();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_node;
        break;
      }

      // repeated .CodeBreeder.NodeProto node = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_node:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_node()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_node;
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void StateProto::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required uint64 state_id = 1;
  if (has_state_id()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(1, this->state_id(), output);
  }

  // repeated .CodeBreeder.NodeProto node = 2;
  for (int i = 0; i < this->node_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->node(i), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* StateProto::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required uint64 state_id = 1;
  if (has_state_id()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(1, this->state_id(), target);
  }

  // repeated .CodeBreeder.NodeProto node = 2;
  for (int i = 0; i < this->node_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        2, this->node(i), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int StateProto::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required uint64 state_id = 1;
    if (has_state_id()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt64Size(
          this->state_id());
    }

  }
  // repeated .CodeBreeder.NodeProto node = 2;
  total_size += 1 * this->node_size();
  for (int i = 0; i < this->node_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->node(i));
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void StateProto::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const StateProto* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const StateProto*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void StateProto::MergeFrom(const StateProto& from) {
  GOOGLE_CHECK_NE(&from, this);
  node_.MergeFrom(from.node_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_state_id()) {
      set_state_id(from.state_id());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void StateProto::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void StateProto::CopyFrom(const StateProto& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool StateProto::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  return true;
}

void StateProto::Swap(StateProto* other) {
  if (other != this) {
    std::swap(state_id_, other->state_id_);
    node_.Swap(&other->node_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata StateProto::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = StateProto_descriptor_;
  metadata.reflection = StateProto_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int PoolProto::kNameFieldNumber;
const int PoolProto::kTypeProtoFieldNumber;
const int PoolProto::kQualifiedNameFieldNumber;
#endif  // !_MSC_VER

PoolProto::PoolProto()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void PoolProto::InitAsDefaultInstance() {
}

PoolProto::PoolProto(const PoolProto& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void PoolProto::SharedCtor() {
  _cached_size_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

PoolProto::~PoolProto() {
  SharedDtor();
}

void PoolProto::SharedDtor() {
  if (this != default_instance_) {
  }
}

void PoolProto::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* PoolProto::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return PoolProto_descriptor_;
}

const PoolProto& PoolProto::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_synth_2eproto();
  return *default_instance_;
}

PoolProto* PoolProto::default_instance_ = NULL;

PoolProto* PoolProto::New() const {
  return new PoolProto;
}

void PoolProto::Clear() {
  name_.Clear();
  type_proto_.Clear();
  qualified_name_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool PoolProto::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated string name = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_name:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->add_name()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->name(this->name_size() - 1).data(),
            this->name(this->name_size() - 1).length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(10)) goto parse_name;
        if (input->ExpectTag(18)) goto parse_type_proto;
        break;
      }

      // repeated .CodeBreeder.TypeProto type_proto = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_type_proto:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_type_proto()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_type_proto;
        if (input->ExpectTag(26)) goto parse_qualified_name;
        break;
      }

      // repeated string qualified_name = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_qualified_name:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->add_qualified_name()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->qualified_name(this->qualified_name_size() - 1).data(),
            this->qualified_name(this->qualified_name_size() - 1).length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(26)) goto parse_qualified_name;
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void PoolProto::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // repeated string name = 1;
  for (int i = 0; i < this->name_size(); i++) {
  ::google::protobuf::internal::WireFormat::VerifyUTF8String(
    this->name(i).data(), this->name(i).length(),
    ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      1, this->name(i), output);
  }

  // repeated .CodeBreeder.TypeProto type_proto = 2;
  for (int i = 0; i < this->type_proto_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->type_proto(i), output);
  }

  // repeated string qualified_name = 3;
  for (int i = 0; i < this->qualified_name_size(); i++) {
  ::google::protobuf::internal::WireFormat::VerifyUTF8String(
    this->qualified_name(i).data(), this->qualified_name(i).length(),
    ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      3, this->qualified_name(i), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* PoolProto::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // repeated string name = 1;
  for (int i = 0; i < this->name_size(); i++) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->name(i).data(), this->name(i).length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target = ::google::protobuf::internal::WireFormatLite::
      WriteStringToArray(1, this->name(i), target);
  }

  // repeated .CodeBreeder.TypeProto type_proto = 2;
  for (int i = 0; i < this->type_proto_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        2, this->type_proto(i), target);
  }

  // repeated string qualified_name = 3;
  for (int i = 0; i < this->qualified_name_size(); i++) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->qualified_name(i).data(), this->qualified_name(i).length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target = ::google::protobuf::internal::WireFormatLite::
      WriteStringToArray(3, this->qualified_name(i), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int PoolProto::ByteSize() const {
  int total_size = 0;

  // repeated string name = 1;
  total_size += 1 * this->name_size();
  for (int i = 0; i < this->name_size(); i++) {
    total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
      this->name(i));
  }

  // repeated .CodeBreeder.TypeProto type_proto = 2;
  total_size += 1 * this->type_proto_size();
  for (int i = 0; i < this->type_proto_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->type_proto(i));
  }

  // repeated string qualified_name = 3;
  total_size += 1 * this->qualified_name_size();
  for (int i = 0; i < this->qualified_name_size(); i++) {
    total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
      this->qualified_name(i));
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void PoolProto::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const PoolProto* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const PoolProto*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void PoolProto::MergeFrom(const PoolProto& from) {
  GOOGLE_CHECK_NE(&from, this);
  name_.MergeFrom(from.name_);
  type_proto_.MergeFrom(from.type_proto_);
  qualified_name_.MergeFrom(from.qualified_name_);
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void PoolProto::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void PoolProto::CopyFrom(const PoolProto& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PoolProto::IsInitialized() const {

  return true;
}

void PoolProto::Swap(PoolProto* other) {
  if (other != this) {
    name_.Swap(&other->name_);
    type_proto_.Swap(&other->type_proto_);
    qualified_name_.Swap(&other->qualified_name_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata PoolProto::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = PoolProto_descriptor_;
  metadata.reflection = PoolProto_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int TrainingProto::kPoolProtoFieldNumber;
const int TrainingProto::kPositiveFieldNumber;
const int TrainingProto::kNegativeFieldNumber;
const int TrainingProto::kPropertyFeaturesFieldNumber;
const int TrainingProto::kEvoCodeFieldNumber;
const int TrainingProto::kEvoOutputFieldNumber;
const int TrainingProto::kTypeStringFieldNumber;
#endif  // !_MSC_VER

TrainingProto::TrainingProto()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void TrainingProto::InitAsDefaultInstance() {
  pool_proto_ = const_cast< ::CodeBreeder::PoolProto*>(&::CodeBreeder::PoolProto::default_instance());
}

TrainingProto::TrainingProto(const TrainingProto& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void TrainingProto::SharedCtor() {
  _cached_size_ = 0;
  pool_proto_ = NULL;
  evo_code_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  evo_output_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  type_string_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

TrainingProto::~TrainingProto() {
  SharedDtor();
}

void TrainingProto::SharedDtor() {
  if (evo_code_ != &::google::protobuf::internal::kEmptyString) {
    delete evo_code_;
  }
  if (evo_output_ != &::google::protobuf::internal::kEmptyString) {
    delete evo_output_;
  }
  if (type_string_ != &::google::protobuf::internal::kEmptyString) {
    delete type_string_;
  }
  if (this != default_instance_) {
    delete pool_proto_;
  }
}

void TrainingProto::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* TrainingProto::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return TrainingProto_descriptor_;
}

const TrainingProto& TrainingProto::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_synth_2eproto();
  return *default_instance_;
}

TrainingProto* TrainingProto::default_instance_ = NULL;

TrainingProto* TrainingProto::New() const {
  return new TrainingProto;
}

void TrainingProto::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (has_pool_proto()) {
      if (pool_proto_ != NULL) pool_proto_->::CodeBreeder::PoolProto::Clear();
    }
    if (has_evo_code()) {
      if (evo_code_ != &::google::protobuf::internal::kEmptyString) {
        evo_code_->clear();
      }
    }
    if (has_evo_output()) {
      if (evo_output_ != &::google::protobuf::internal::kEmptyString) {
        evo_output_->clear();
      }
    }
    if (has_type_string()) {
      if (type_string_ != &::google::protobuf::internal::kEmptyString) {
        type_string_->clear();
      }
    }
  }
  positive_.Clear();
  negative_.Clear();
  property_features_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool TrainingProto::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional .CodeBreeder.PoolProto pool_proto = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_pool_proto()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_positive;
        break;
      }

      // repeated .CodeBreeder.StateProto positive = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_positive:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_positive()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_positive;
        if (input->ExpectTag(26)) goto parse_negative;
        break;
      }

      // repeated .CodeBreeder.StateProto negative = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_negative:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_negative()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(26)) goto parse_negative;
        if (input->ExpectTag(32)) goto parse_property_features;
        break;
      }

      // repeated bool property_features = 4;
      case 4: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_property_features:
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 1, 32, input, this->mutable_property_features())));
        } else if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag)
                   == ::google::protobuf::internal::WireFormatLite::
                      WIRETYPE_LENGTH_DELIMITED) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitiveNoInline<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, this->mutable_property_features())));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(32)) goto parse_property_features;
        if (input->ExpectTag(42)) goto parse_evo_code;
        break;
      }

      // optional string evo_code = 5;
      case 5: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_evo_code:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_evo_code()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->evo_code().data(), this->evo_code().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(50)) goto parse_evo_output;
        break;
      }

      // optional string evo_output = 6;
      case 6: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_evo_output:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_evo_output()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->evo_output().data(), this->evo_output().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(58)) goto parse_type_string;
        break;
      }

      // optional string type_string = 7;
      case 7: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_type_string:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_type_string()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->type_string().data(), this->type_string().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void TrainingProto::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // optional .CodeBreeder.PoolProto pool_proto = 1;
  if (has_pool_proto()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->pool_proto(), output);
  }

  // repeated .CodeBreeder.StateProto positive = 2;
  for (int i = 0; i < this->positive_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->positive(i), output);
  }

  // repeated .CodeBreeder.StateProto negative = 3;
  for (int i = 0; i < this->negative_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      3, this->negative(i), output);
  }

  // repeated bool property_features = 4;
  for (int i = 0; i < this->property_features_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(
      4, this->property_features(i), output);
  }

  // optional string evo_code = 5;
  if (has_evo_code()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->evo_code().data(), this->evo_code().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      5, this->evo_code(), output);
  }

  // optional string evo_output = 6;
  if (has_evo_output()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->evo_output().data(), this->evo_output().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      6, this->evo_output(), output);
  }

  // optional string type_string = 7;
  if (has_type_string()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->type_string().data(), this->type_string().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      7, this->type_string(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* TrainingProto::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // optional .CodeBreeder.PoolProto pool_proto = 1;
  if (has_pool_proto()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        1, this->pool_proto(), target);
  }

  // repeated .CodeBreeder.StateProto positive = 2;
  for (int i = 0; i < this->positive_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        2, this->positive(i), target);
  }

  // repeated .CodeBreeder.StateProto negative = 3;
  for (int i = 0; i < this->negative_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        3, this->negative(i), target);
  }

  // repeated bool property_features = 4;
  for (int i = 0; i < this->property_features_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteBoolToArray(4, this->property_features(i), target);
  }

  // optional string evo_code = 5;
  if (has_evo_code()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->evo_code().data(), this->evo_code().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        5, this->evo_code(), target);
  }

  // optional string evo_output = 6;
  if (has_evo_output()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->evo_output().data(), this->evo_output().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        6, this->evo_output(), target);
  }

  // optional string type_string = 7;
  if (has_type_string()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->type_string().data(), this->type_string().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        7, this->type_string(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int TrainingProto::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional .CodeBreeder.PoolProto pool_proto = 1;
    if (has_pool_proto()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->pool_proto());
    }

    // optional string evo_code = 5;
    if (has_evo_code()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->evo_code());
    }

    // optional string evo_output = 6;
    if (has_evo_output()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->evo_output());
    }

    // optional string type_string = 7;
    if (has_type_string()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->type_string());
    }

  }
  // repeated .CodeBreeder.StateProto positive = 2;
  total_size += 1 * this->positive_size();
  for (int i = 0; i < this->positive_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->positive(i));
  }

  // repeated .CodeBreeder.StateProto negative = 3;
  total_size += 1 * this->negative_size();
  for (int i = 0; i < this->negative_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->negative(i));
  }

  // repeated bool property_features = 4;
  {
    int data_size = 0;
    data_size = 1 * this->property_features_size();
    total_size += 1 * this->property_features_size() + data_size;
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void TrainingProto::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const TrainingProto* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const TrainingProto*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void TrainingProto::MergeFrom(const TrainingProto& from) {
  GOOGLE_CHECK_NE(&from, this);
  positive_.MergeFrom(from.positive_);
  negative_.MergeFrom(from.negative_);
  property_features_.MergeFrom(from.property_features_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_pool_proto()) {
      mutable_pool_proto()->::CodeBreeder::PoolProto::MergeFrom(from.pool_proto());
    }
    if (from.has_evo_code()) {
      set_evo_code(from.evo_code());
    }
    if (from.has_evo_output()) {
      set_evo_output(from.evo_output());
    }
    if (from.has_type_string()) {
      set_type_string(from.type_string());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void TrainingProto::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void TrainingProto::CopyFrom(const TrainingProto& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TrainingProto::IsInitialized() const {

  for (int i = 0; i < positive_size(); i++) {
    if (!this->positive(i).IsInitialized()) return false;
  }
  for (int i = 0; i < negative_size(); i++) {
    if (!this->negative(i).IsInitialized()) return false;
  }
  return true;
}

void TrainingProto::Swap(TrainingProto* other) {
  if (other != this) {
    std::swap(pool_proto_, other->pool_proto_);
    positive_.Swap(&other->positive_);
    negative_.Swap(&other->negative_);
    property_features_.Swap(&other->property_features_);
    std::swap(evo_code_, other->evo_code_);
    std::swap(evo_output_, other->evo_output_);
    std::swap(type_string_, other->type_string_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata TrainingProto::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = TrainingProto_descriptor_;
  metadata.reflection = TrainingProto_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace CodeBreeder

// @@protoc_insertion_point(global_scope)
