/* Copyright 2017 Google Inc. All Rights Reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
==============================================================================*/

#include ZZ_Prelude_hh
#include "TypeInference.hh"
#include "zz/Generics/IntMap.hh"
#include "Vm.hh"
#include "Parser.hh"

// Type inference in Evo is greatly simplified by the fact that all symbols are fully typed at the
// point of introduction (i.e. 'var' or 'cnst' statement). Although "fully typed" may include
// type-variables for constants ('cnst nil<`T> = List<`T>.0(); fun id<`A>(x :`A){x}'), those
// type-variables are always qualified with ground types when used ('id<List<Int>>(nil<Int>)').

#define EXTENDED_INFERENCE

namespace ZZ {
using namespace std;


ZZ_PTimer_Add(evo_type_inference);


//mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm
// Type function:


enum DefKind {
    def_NULL,

    // Types:
    def_BitP,   // built-in primitive type (nullary)
    def_BitC,   // built-in composite type (any arity allowed; will be correct by construction)
    def_TypeO,  // original, unprocessed typedef
    def_TypeX,  // (used during expansion to catch cycles)
    def_Type,   // final typedef, fully expanded
    def_Data,   // datadef
    def_TVar,

    // Exprs:
    def_Cnst,   // "rec" definition, may or may not have parameters
    def_Var,    // "let" definition, never has parameters
    DefKind_size
};

static cchar* DefKind_names[DefKind_size] = {
    "NULL",
    "BitP",
    "BitC",
    "TypeO",
    "TypeX",
    "Type",
    "Data",
    "TVar",
    "Cnst",
    "Var",
};


// Function from a list of types to a type.
struct TypeFun {
    DefKind   kind;     // -- the type function originates from this kind of construct
    Arr<Type> params;   // -- type parameters (formals to be replaced)
    Type      def;      // -- parameterized types (contains type-variables from 'params')
    Loc       loc;      // -- definition location

    TypeFun(DefKind kind = def_NULL, Arr<Type> params = Arr<Type>(), Type def = Type(), Loc loc = Loc())
        : kind(kind), params(params), def(def), loc(loc) {}

    explicit operator bool() const { return kind != def_NULL; }

    Type operator()(Arr<Type> const& targs) const {
        return ((+params).size() == 0) ? def : typeSubst(def, params, targs); }

    void checkArity(Type const& type) const {  // -- throws an exception if type symbol is applied to wrong number of arguments
        if (kind == def_BitC) return;  // -- correct by construction (these types are only generated by the parser)
        uint ps = (+params).size();
        uint as = (+type.args).size();
        if (ps != as) throw Excp_ParseError(fmt("%_: Wrong number of type-arguments given to '%_' (should be %_).", type.loc, type.name, ps));
    }

    /*DEBUG*/bool operator==(TypeFun const& h) const { return kind == h.kind && vecEqual(+params, +h.params) && def == h.def /*&& loc == h.loc*/; }
};

template<> fts_macro void write_(Out& out, const TypeFun& v) {
    wr(out, "TypeFun{kind=%_; params=%_; def=%_; loc=%_}", DefKind_names[v.kind], v.params, v.def, v.loc); }


//mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm
// Inference helpers:


static void expandTypedef(Type& type, SymTable<TypeFun> const& tab)
{
    if (type.isTVar()) return;

    TypeFun const& h = tab[type];
    if (h.kind == def_Type){
        h.checkArity(type);
        type = h(type.args);
    }else if (h.kind == def_Data)
        h.checkArity(type);

    for (Type& t : +type.args)
        expandTypedef(t, tab);
}


static void expandTypedefInExpr(Expr& expr, SymTable<TypeFun> const& tab)
{
    if (expr.type)
        expandTypedef(expr.type, tab);
    for (Type& t : +expr.targs)
        expandTypedef(t, tab);
    for (Expr& e : expr)
        expandTypedefInExpr(e, tab);
}


static void expandTypedefInSymTable(Type const& type, SymTable<TypeFun>& tab)
{
    if (type.isTVar()) return;

    TypeFun& h = tab.ref(type.name);
    if (h.kind == def_TypeO){
        // Recursively expand all typedefs we depend on:
        h.kind = def_TypeX;
        expandTypedefInSymTable(h.def, tab);
        h.kind = def_Type;      // -- safe to use reference 'h' still since 'tab' was not grown (otherwise could have been reallocated)

        expandTypedef(h.def, tab);  // -- update our own definition, using up-to-date typedefs

    }else if (h.kind == def_TypeX)
        throw Excp_ParseError(fmt("%_: Recursive typedef of symbol '%_'.", h.loc, type.name));

    for (Type const& t : type)
        expandTypedefInSymTable(t, tab);
}


static void checkArities(Type const& type, SymTable<TypeFun> const& tab)
{
    if (!type.isTVar()){
        tab[type].checkArity(type);
        for (Type const& t : +type.args)
            checkArities(t, tab);
    }
}


// Throws an 'Excp_ParseError' if 'type' is invalid.
void checkValidType(Type const& type, SymTable<TypeFun> const& tab)
{
    tab[type];  // -- will throw exception if 'type' is not in symbol table
    for (Type const& t : type){
        if (!t) throw Excp_ParseError(fmt("%_: Incomplete type, possibly from failed type derivation.", type.loc));
        checkValidType(t, tab);
    }
}


// For T = {T0, T1, T2, ...}
//   case< T,R> : (T,  T0->R,  T1->R, ...) -> R
//   case<&T,R> : (T, &T0->R, &T1->R, ...) -> R
static Type caseType(Arr<Type> const& targs, Loc err_loc, SymTable<TypeFun> const& tab)
{
    if (!targs || targs.size() != 2) throw Excp_ParseError(fmt("%_: Case expects two type arguments.", err_loc));
    Type ret = targs[1];
    Type split = targs[0];
    bool is_ref = (targs[0].name == a_Ref);
    if (is_ref) split = split[0];
    Type norm = split;
    if (tab[norm].kind == def_Data) norm = tab[norm](norm.args);    // -- normalized type
    if (norm.name != a_OneOf) throw Excp_ParseError(fmt("%_: '%_' can only be applied to sum-types.", err_loc, a_case));

    Vec<Type> in_t;
    in_t.push(split);
    for (Type const& t : norm)
        in_t.push(Type(a_Fun, is_ref ? Type(a_Ref, t) : t, ret));
    return Type(a_Fun, Type(a_Tuple, in_t), ret);
}


// Specialize 'tab' with the type-variable substitution given by 'subs'. Note: no type-variables
// can be present in the global scope, so for efficiency, it is not traversed. Result is a
// flattened version of 'tab' (two levels: global + local).
static SymTable<TypeFun> specializeSymTable(SymTable<TypeFun> const& tab0, Vec<TSubst> const& subs)
{
    SymTable<TypeFun> ret;
    Vec<Type> from;
    Vec<Type> into;

    for (SymTable<TypeFun> const* tab = &tab0;; tab = tab->getParent()){
        if (tab->getParent() == nullptr){
            ret.setParent(tab);
            return ret; }

        for (Atom name : tab->locals()){
            if (!ret.has(name)){
                TypeFun const& src = tab->ref(name);
                if (src.kind == def_Var){
                    // Convert free type-variables of 'src.def' (not in 'src.params') using 'subs':
                    from.clear();
                    into.clear();
                    for (TSubst s : subs){
                        if (!has(+src.params, s.a)){
                            from.push(s.a);
                            into.push(s.ty); }
                    }
                    Type new_def = typeSubst(src.def, from, into);
                    ret.addQ(name, TypeFun(def_Var, src.params, new_def, src.loc));
                }else
                    ret.addQ(name, src);
            }
        }
    }
}


static void addFreeTypeVars(Type const& type, SymTable<TypeFun>& tab) {
    if (type.isTVar()){
        if (!tab.has(type.name))
            tab.add(type.name, TypeFun(def_TVar));
    }else if (type.args){
        for (Type const& t : type)
            addFreeTypeVars(t, tab);
    }
}


//mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm
// Actual inference:


static Type inferTypes(Expr& expr, SymTable<TypeFun>& tab, Type ctx_type = Type(), bool global_block = false);


//=================================================================================================
#if defined(EXTENDED_INFERENCE)


// Type arguments will be added to 'fun_sym'
static Type matchArgs(Expr& fun_sym, Type const& arg_type, SymTable<TypeFun>& tab)
{
    assert(fun_sym.name != a_case);     // <<== BI
    Arr<Type> targs = tab[fun_sym].params;   // -- array: [A, B, C]
    Type      def   = tab[fun_sym].def;      // -- type expression: '(A, &B, A->C) -> B'
    Arr<Type> subst(reserve_, targs.size()); // -- will be populated with substitutions for 'targs'

    function<void(Type const&, Type const&)> match = [&](Type const& def, Type const& arg) {
        if (!def || !arg) return;
        if (def.isTVar()){
            uind pos = search(targs, def);
            if (pos == UIND_MAX) return;
            if (subst[pos]){
                if (subst[pos] != arg) throw Excp_ParseError(fmt("%_: Type-variable '%_' inferred to both '%_' and '%_'.", fun_sym.loc, def, subst[pos], arg));
            }else
                subst[pos] = arg;
        }else{
            if (def.name != arg.name || def.size() != arg.size())
                throw Excp_ParseError(fmt("%_: Argument of type '%_' cannot match '%_'.", fun_sym.loc, arg, def));
            for (uint i = 0; i < def.size(); i++)
                match(def[i], arg[i]);
        }
    };

    assert(def.name == a_Fun);
    match(def[0], arg_type);

    for (uint i = 0; i < targs.size(); i++)
        if (!subst[i])
            throw Excp_ParseError(fmt("%_: Could not determine type-var '%_' of '%_<%_>' using simple inference rules, please use fully qualified syntax.", fun_sym.loc, targs[i], fun_sym, join(", ", targs)));

    fun_sym.targs = subst;
    if (fun_sym.name == a_case) // <<== BI
        return caseType(subst, fun_sym.loc, tab);

    return typeSubst(def, targs, subst);
}


static Type tryInferType(Expr& expr, SymTable<TypeFun>& tab)
{
    try{
        return inferTypes(expr, tab);
    }catch (Excp_ParseError){   // -- slightly inefficient
        return Type();
    }
};


static Type inferFunType(Expr& expr, SymTable<TypeFun>& tab)
{
    Expr& fun = expr[0];
    Expr& arg = expr[1];

    // Can we infer type without looking at argument?
    if (fun.kind != expr_Sym)
        return inferTypes(fun, tab);    // -- if not a symbol, we must know the type

    uint as = (+fun.targs).size();          // -- number of actually provided type parameters
    if (fun.name == a_case && !tab.has(a_case)){// <<== BI
        if (!tab.has(a_case) && as != 0)
            return inferTypes(fun, tab);
        else{
            if (arg.size() == 0) throw Excp_ParseError(fmt("%_: '%_' takes at least two arguments.", arg.loc, a_case));
            Type ty_T = inferTypes(arg[0], tab);
            Type norm = ty_T;
            if (tab[norm].kind == def_Data) norm = tab[norm](norm.args);    // -- normalized type
            if (norm.name != a_OneOf) throw Excp_ParseError(fmt("%_: '%_' can only be applied to sum-types.", arg[0].loc, a_case));
            if (arg[1].kind == expr_Lamb)
                if (!arg[1][0].type)
                    arg[1][0].type = norm[0];   // -- this should allow a lambda term derive return type
            Type ty_arg1 = inferTypes(arg[1], tab);
            if (ty_arg1.name != a_Fun) throw Excp_ParseError(fmt("%_: Args 1..n of a '%_' must be functions.", arg[1].loc, a_case));
            Type ty_R = ty_arg1[1];
            fun.targs = Arr<Type>({ty_T, ty_R});
            return inferTypes(fun, tab);
        }

    }else{
        uint ps = (+tab[fun].params).size();    // -- number of formal type parameters
        if (as != 0 || ps == 0)
            return inferTypes(fun, tab);
        else{
            // Here we have a function symbol with >0 type-parameters, but none given:
            if (arg.kind == expr_Tuple){
                Vec<Type> ts = map(arg, [&tab](Expr& e){ return tryInferType(e, tab); });
                return fun.type = matchArgs(fun, Type(a_Tuple, ts).setLoc(arg.loc), tab);
            }else{
                return fun.type = matchArgs(fun, tryInferType(arg, tab), tab); }
        }
    }
}


#endif
//=================================================================================================


// 'pat' is a pattern (nested tuple of variables symbols), and 'type' is a type of compatible structure
static void imbueTypes(Expr& pat, Type const& type)
{
    if (pat.kind == expr_Sym){
        assert(!pat.targs);
        if (pat.type && pat.type != type)
            throw Excp_ParseError(fmt("%_: Symbol '%_' has conflicting types '%_' and '%_'.", pat.loc, pat, type, pat.type));
        //assert(!pat.type || pat.type == type);
        pat.type = type;
    }else{ assert(pat.kind == expr_Tuple);
        if (type.name == a_Void && pat.size() == 0)
            pat.type = type;
        else{
            if (type.name != a_Tuple || type.size() != pat.size())
                throw Excp_ParseError(fmt("%_: Pattern '%_' does not match type '%_'.", pat.loc, pat, type));
            Vec<Type> ts;
            for (uint i = 0; i < pat.size(); i++){
                imbueTypes(pat[i], type[i]);
                ts.push(pat[i].type); }
            pat.type = Type(a_Tuple, ts);
        }
    }
}


// 'vars' is a typed pattern
static void addVarsToSymTable(Expr const& vars, SymTable<TypeFun>& tab)
{
    if (vars.kind == expr_Sym){
        assert(!vars.targs); assert(vars.type);
        tab.add(vars.name, TypeFun(def_Var, Arr<Type>(), vars.type, vars.loc));
    }else{ assert(vars.kind == expr_Tuple);
        for (Expr const & e : vars)
            addVarsToSymTable(e, tab);
    }
}


/*
Types are pushed down ("ctx_type") for:
  - RHS of rec/let definitions (if type is specified)
  - Argument tuple of function application (the "x" in "f x") (always)
  - Formal arguments of a lambda header (for "\" but not for "\:")
  - MkVec
*/


// NOTE! Symbol table 'tab' is updated by 'LetDef's.
static Type inferTypes(Expr& expr, SymTable<TypeFun>& tab, Type ctx_type, bool global_block)
{
    if (ctx_type.name == a_Any)
        ctx_type = Type();

    // For non-definitional expression, check validity of type, if given:
    if (expr.type && expr.kind != expr_TypeDef && expr.kind != expr_DataDef && expr.kind != expr_RecDef){
        if (!expr.type.loc) expr.type.setLoc(expr.loc); // -- for error message in failed 'checkValidType()'
        checkValidType(expr.type, tab); }

    // Infer type for expression type:
    switch (expr.kind){
    case expr_Sym:
        //assert(!expr.type);     // -- only place where types are given are typed-pattern, which should not be part of type inference (note! commented out: 'inferFunType()' changes this)
        for (Type const& t : +expr.targs)
            checkValidType(t, tab);
        if (expr.name == a_case && !tab.has(a_case))    // <<== BI
            expr.type = caseType(expr.targs, expr.loc, tab);
        else{
            uint ps = (+tab[expr].params).size();
            uint as = (+expr.targs).size();
            // <<== if 'as == 0', use 'ctx_type' here
            if (ps != as)
                throw Excp_ParseError((as == 0) ? fmt("%_: Missing type-arguments to '%_'.", expr.loc, expr.name) :
                                                  fmt("%_: Wrong number of type-arguments given to '%_' (should be %_).", expr.loc, expr.name, ps));
            expr.type = tab[expr](expr.targs);
        }
        break;

    case expr_Tuple:{
        Array<Type const> ts;
        if (ctx_type){
            ts = (ctx_type.name == a_Void)  ? Array<Type const>(empty_) :
                 (ctx_type.name != a_Tuple) ? Array<Type const>(&ctx_type, 1) : ctx_type.args.slice();
            if (expr.size() != ts.size()) throw Excp_ParseError(fmt("%_: Tuple size does not match context type '%_'", expr.loc, ctx_type));
        }

        if (expr.size() == 0)
            expr.type = Type(a_Void);
        else{
            assert(expr.size() != 1);
            Vec<Type> ds;
            for (uint i = 0; i < expr.size(); i++)
                ds.push(inferTypes(expr[i], tab, ts ? ts[i] : Type()));
            expr.type = Type(a_Tuple, ds);
        }
        break; }

    case expr_MkRef:
        inferTypes(expr[0], tab);
        expr.type = Type(a_Ref, expr[0].type);
        break;

    case expr_Deref:
        if (inferTypes(expr[0], tab).name != a_Ref)
            throw Excp_ParseError(fmt("%_: Trying to dereference non-reference type '%_'.", expr.loc, expr[0].type));
        expr.type = expr[0].type[0];
        break;

    case expr_Appl:{
        if (expr[0].kind == expr_Sym && expr[0].name == a_write){
            // Special builtin 'write_' must take argument:
            Type arg_t = inferTypes(expr[1], tab);
            expr[0].type = Type(a_Fun, Type(arg_t), Type(a_Void));
            expr.type = Type(a_Void);
            break;
        }

      #if defined(EXTENDED_INFERENCE)
        Type fun_t = inferFunType(expr, tab);
      #else
        Type fun_t = inferTypes(expr[0], tab);
      #endif
        if (fun_t.name != a_Fun) throw Excp_ParseError(fmt("%_: Expression is not a function (type is '%_').", expr[0].loc, fun_t));
        Type arg_t = inferTypes(expr[1], tab, fun_t[0]);
        expr.type = fun_t[1];
        break; }

    case expr_Cons:{
        uint sel_idx = stringToUInt64(Str(expr.name));
        Type const& t = expr.targs[0];
        Type t_norm = (tab[t].kind == def_Data) ? tab[t](t.args) : t;   // -- expand datadefs
        if (t_norm.name != a_OneOf) throw Excp_ParseError(fmt("%_: Sum-type constructors can only be used on sum-types, not '%_'.", expr.loc, t));
        if (sel_idx >= t_norm.size()) throw Excp_ParseError(fmt("%_: Index '%_' is out-of-range. Sum-type has %_ alternatives.", expr.loc, sel_idx, t_norm.size()));
        expr.type = Type(a_Fun, t_norm[sel_idx], t);
        break; }

    case expr_Sel:{
        Type t = inferTypes(expr[0], tab);
        bool is_ref = (t.name == a_Ref);
        if (is_ref) t = t[0];
        if (t.name != a_Tuple) throw Excp_ParseError(fmt("%_: Select operator '#' can only be used on tuples, not on type '%_'.", expr.loc, t));
        uint sel_idx = stringToUInt64(Str(expr.name));
        if (sel_idx >= t.size()) throw Excp_ParseError(fmt("%_: Index '%_' is out-of-range. Tuple has arity '%_'.", expr.loc, sel_idx, t.size()));
        expr.type = is_ref ? Type(a_Ref, t[sel_idx]) : t[sel_idx];
        break; }

    case expr_LetDef:
        if (expr.size() == 2){   // -- 'expr[1]' is initial value (optional)
            inferTypes(expr[1], tab, expr.type); assert(!expr.type || expr.type == expr[1].type);
            expr.type = expr[1].type;
        }else
            assert(expr.type);
        imbueTypes(expr[0], expr.type);
        addVarsToSymTable(expr[0], tab);
        break;

    case expr_RecDef:{
        SymTable<TypeFun> stab(tab);
        for (Type const t : +expr[0].targs){
            assert(t.isTVar());
            if (stab.has(t.name)) throw Excp_ParseError(fmt("%_: Nested type-variables must be distinct, '%_' used in outer scope.", t.loc, t));
            stab.add(t.name, TypeFun(def_TVar));
        }
        checkValidType(expr.type, stab);
        inferTypes(expr[1], stab, expr.type);    // -- 'expr[1]' is initial value
        break; }

    case expr_MkVec:
        assert(expr.type && expr.type.name == a_Vec);
        for (Expr& e : expr)
            inferTypes(e, tab, expr.type[0]);
        break;

    case expr_Lit:
    case expr_TypeDef:
    case expr_DataDef:
        /*nothing to do*/;
        break;

    case expr_Lamb:{
        Expr& head = expr[0];
        Expr& body = expr[1];

        if (head.isUnit() && !head.type) head.type = Type(a_Void).setLoc(head.loc);
        if (head.type && !expr.type) expr.type = Type(a_Fun, head.type, Type());    // -- use partial type; will be completed
        if (!expr.type && !ctx_type) throw Excp_ParseError(fmt("%_: Untyped lambda header used in type free context; use \"\\:\" instead.", expr.loc));

        //Type const& type = expr.type ? expr.type : ctx_type;
        /**/Type const& type = ctx_type ? ctx_type : expr.type;

        if (type.name != a_Fun) throw Excp_ParseError(fmt("%_: Lambda expression cannot match type: %_", expr.loc, type));
        imbueTypes(head, type[0]);

        SymTable<TypeFun> sub_tab(tab);
        addVarsToSymTable(head, sub_tab);
        inferTypes(body, sub_tab, type[1]);
        expr.type = Type(a_Fun, head.type, body.type);
        break; }

    case expr_Block:{
        // Add 'rec' types to symbol table:
        SymTable<TypeFun> tab2(tab);
        SymTable<TypeFun>& stab = global_block ? tab : tab2;

        // Infer types for all expressions in block:
        uint j = 0;
        for (uint i = 0; i < expr.size(); i++){
            Expr& e = expr[i];
            if (i >= j && e.kind == expr_RecDef){   // -- trigger on first rec-def only
                for (j = i; j < expr.size() && expr[j].kind == expr_RecDef; j++){
                    Expr& f = expr[j];
                    f[0].type = f.type;
                    // <<== template specialization test goes here
                    stab.add(f[0].name, TypeFun(def_Cnst, f[0].targs, f[0].type, f[0].loc));
                }
            }
            bool last = (i == expr.size() - 1) && expr[i].kind != expr_RecDef;
            inferTypes(e, stab, last ? ctx_type : Type());
        }
        bool no_last = (expr.size() == 0 || expr[expr.size()-1].kind == expr_RecDef);   // -- rec-defs have a flexible evaluation order
        expr.type = no_last ? Type(a_Void).setLoc(expr.loc) : expr[expr.size()-1].type; // -- last expression determines type of sequence expression
        break; }

    case expr_MetaIf:{
        if (expr[0].kind != expr_Sym || expr[0].name != a_match || expr[0].targs.psize() != 2)
            throw Excp_ParseError(fmt("%_: Expected 'match<GenericType, SpecializedType>'.", expr[0].loc));
        Vec<TSubst> subs;
        Type const& t_gen  = expr[0].targs[0];
        Type const& t_spec = expr[0].targs[1];
        if (!typeMatch(t_gen, t_spec, subs))
            throw Excp_ParseError(fmt("%_: Incongruent type shapes; types can never match.", expr[0].loc));
        for (TSubst s : subs)
            checkValidType(s.a, tab);

        SymTable<TypeFun> tab_match = specializeSymTable(tab, subs);
        addFreeTypeVars(t_spec, tab_match);

        inferTypes(expr[1], tab_match, typeSubst(ctx_type, subs));
        inferTypes(expr[2], tab      , ctx_type);
        expr.type = expr[2].type;
        break; }

    case expr_MetaErr:{
        expr.type = ctx_type ? ctx_type : Type(a_Void);    // -- no type-checking
        break; }

    default: assert(false); }
    assert(expr.type);

    // Check type consistency:
    if (ctx_type && expr.type != ctx_type){
        throw Excp_ParseError(fmt("%_: Type mismatch. Context demands '%_' but expression is '%_'.", expr.loc, ctx_type, expr.type)); }

    if (!expr.type.loc) expr.type.setLoc(expr.loc);     // -- assign a location to derived types
    return expr.type;
}

//mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm
// Main:


struct Inferrer_data {
    SymTable<TypeFun> tab;
    Vec<uind> undo;
};


Inferrer::Inferrer()
{
    data = new Inferrer_data;

    SymTable<TypeFun>& tab = data->tab;

    // Add built-in types:
    Arr<Type> nullary({});
    for (Atom name : bit_primitive) tab.add(name, TypeFun(def_BitP));
    for (Atom name : bit_composite) tab.add(name, TypeFun(def_BitC));

    // Add built-in functions:
    for (Pair<Atom, Type> p : getBuiltinFunctions())
        tab.add(p.fst, TypeFun(def_Cnst, {}, p.snd));

    Type tvar_A  = Type(Atom("A"));      // <<== BI
    Type tvar_TT = Type(Atom("TT"));
    tab.add(a_ite   , TypeFun(def_Cnst, {tvar_A}, parseType("(Bool, A, A) -> A")));
    tab.add(a_assign, TypeFun(def_Cnst, {tvar_A}, parseType("(&A, A) -> Void")));
    tab.add(a_fail  , TypeFun(def_Cnst, {tvar_A}, tvar_A));
    tab.add(a_run   , TypeFun(def_Cnst, {tvar_A}, parseType("(Void->A, Int, Int, Int) -> A")));

    tab.add(a_size  , TypeFun(def_Cnst, {tvar_A}, parseType("[A] -> Int")));
    tab.add(a_get   , TypeFun(def_Cnst, {tvar_A}, parseType("([A], Int) -> A")));
    tab.add(a_growby, TypeFun(def_Cnst, {tvar_A}, parseType("([A], Int) -> Void")));
    tab.add(a_resize, TypeFun(def_Cnst, {tvar_A}, parseType("([A], Int) -> Void")));
    tab.add(a_set   , TypeFun(def_Cnst, {tvar_A}, parseType("([A], Int, A) -> Void")));

    tab.add(a_print_bool , TypeFun(def_Cnst, {}, parseType("Bool  -> Void")));
    tab.add(a_print_int  , TypeFun(def_Cnst, {}, parseType("Int   -> Void")));
    tab.add(a_print_float, TypeFun(def_Cnst, {}, parseType("Float -> Void")));
    tab.add(a_print_atom , TypeFun(def_Cnst, {}, parseType("Atom  -> Void")));

    tab.add(a_try   , TypeFun(def_Cnst, {tvar_A, tvar_TT}, parseType("(Void->A, TT->A) -> A")));
    tab.add(a_throw , TypeFun(def_Cnst, {tvar_A, tvar_TT}, parseType("TT -> A")));
    tab.add(a_ttry  , TypeFun(def_Cnst, {tvar_A, tvar_TT}, parseType("(Atom, Void->A, TT->A) -> A")));
    tab.add(a_tthrow, TypeFun(def_Cnst, {tvar_A, tvar_TT}, parseType("(Atom, TT) -> A")));

    tab.add(a_line , TypeFun(def_Cnst, {}, parseType("Int")));
    tab.add(a_file , TypeFun(def_Cnst, {}, parseType("Atom")));

    tab.add(a_block , TypeFun(def_Cnst, {tvar_A}, parseType("A -> A")));
    tab.add(a_break , TypeFun(def_Cnst, {tvar_A}, parseType("A -> Void")));
}


Inferrer::~Inferrer() {
    delete data; }


void Inferrer::push() {
    data->undo.push(data->tab.size()); }


void Inferrer::pop() {
    while (data->tab.size() > data->undo.last()) data->tab.pop();
    data->undo.pop(); }


Type Inferrer::lookupType(Type const& type) {
    return data->tab[type](type.args); }


// Program type inference. Top-level includes typedefs and datadefs not allowed in inner scopes.
void Inferrer::inferTypes(Expr& prog)
{
    ZZ_PTimer_Scope(evo_type_inference);

    SymTable<TypeFun>& tab = data->tab;
    //**/wrLn("INFERENCE SYM TABLE"); tab.dump();

    // Populate symbol table with typedefs and datadefs:
    for (Expr& e : prog){
        bool td = (e.kind == expr_TypeDef);
        if (td || e.kind == expr_DataDef){
            assert(td || e.type.name == a_OneOf);
            // Verify that type-arguments are unique:
            for (uind i = 0; i < e.targs.size(); i++){
                assert(e.targs[i].isTVar());    // -- should be guaranteed by parser
                if (search(e.targs.slice(0, i), e.targs[i]) != UIND_MAX)
                    throw Excp_ParseError(fmt("%_: Type-arguments not unique; symbol '%_' repeated.", e.targs[i].loc, e.targs[i]));
            }

            tab.add(e.name, TypeFun(td ? def_TypeO : def_Data, e.targs, e.type, e.loc));
        }
    }

    // Check arity of type applications in definitions:
    for (Expr& e : prog)
        if (e.kind == expr_TypeDef || e.kind == expr_DataDef)
            checkArities(e.type, tab);

    // Expand typedefs:
    for (Expr& e : prog)
        if (e.kind == expr_TypeDef)
            expandTypedefInSymTable(Type(e.name), tab);
    for (Expr& e : prog)
        if (e.kind != expr_TypeDef /*&& e.kind != expr_DataDef*/)
            expandTypedefInExpr(e, tab);

    // Infer expression types for program:
    ZZ::inferTypes(prog, tab, Type(), /*global_block*/true);
    //**/wrLn("FINAL SYM TABLE"); tab.dump();

    if (getenv("TYPE_INFERRED") || getenv("INFERRED")){
        wrLn("\a*TYPE-INFERRED:\a0\t+\t+");
        wrLn("%_;", join(";\n\n", prog));
        wrLn("\t-\t-");
        newLn();
    }
}


//mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm
}
