# Lint as: python3
"""Tests for deepmath.deephol.utilities.hol_light_sexpression_trees."""
from absl.testing import parameterized
import tensorflow.compat.v1 as tf
from deepmath.deephol.utilities import hol_light_sexpression_syntax as hol
from deepmath.deephol.utilities import hol_light_sexpression_trees
from deepmath.deephol.utilities import sexpression_parser


class SexpressionTypeAtomsTest(parameterized.TestCase):

  @parameterized.parameters(
      ('A', hol.SyntaxElementKind.TYPE, [
          ('A', hol.SyntaxElementKind.TYPE, None, 'enter'),
          ('A', hol.SyntaxElementKind.TYPE, None, 'exit')
      ]),
      ('(bool)', hol.SyntaxElementKind.TYPE, [
          ('(bool)', hol.SyntaxElementKind.TYPE, None, 'enter'),
          ('bool', hol.SyntaxElementKind.TYPE_CONSTRUCTOR_NAME, 0, 'enter'),
          ('bool', hol.SyntaxElementKind.TYPE_CONSTRUCTOR_NAME, 0, 'exit'),
          ('(bool)', hol.SyntaxElementKind.TYPE, None, 'exit'),
      ]),
      ('(fun x y)', hol.SyntaxElementKind.TYPE, [
          ('(fun x y)', hol.SyntaxElementKind.TYPE, None, 'enter'),
          ('fun', hol.SyntaxElementKind.TYPE_CONSTRUCTOR_NAME, 0, 'enter'),
          ('fun', hol.SyntaxElementKind.TYPE_CONSTRUCTOR_NAME, 0, 'exit'),
          ('x', hol.SyntaxElementKind.TYPE, 1, 'enter'),
          ('x', hol.SyntaxElementKind.TYPE, 1, 'exit'),
          ('y', hol.SyntaxElementKind.TYPE, 2, 'enter'),
          ('y', hol.SyntaxElementKind.TYPE, 2, 'exit'),
          ('(fun x y)', hol.SyntaxElementKind.TYPE, None, 'exit'),
      ]),
      ('(c (bool) T)', hol.SyntaxElementKind.TERM, [
          ('(c (bool) T)', hol.SyntaxElementKind.TERM, None, 'enter'),
          ('c', hol.SyntaxElementKind.SEXPRESSION_KIND, 0, 'enter'),
          ('c', hol.SyntaxElementKind.SEXPRESSION_KIND, 0, 'exit'),
          ('(bool)', hol.SyntaxElementKind.TYPE, 1, 'enter'),
          ('bool', hol.SyntaxElementKind.TYPE_CONSTRUCTOR_NAME, 0, 'enter'),
          ('bool', hol.SyntaxElementKind.TYPE_CONSTRUCTOR_NAME, 0, 'exit'),
          ('(bool)', hol.SyntaxElementKind.TYPE, 1, 'exit'),
          ('T', hol.SyntaxElementKind.CONSTANT_NAME, 2, 'enter'),
          ('T', hol.SyntaxElementKind.CONSTANT_NAME, 2, 'exit'),
          ('(c (bool) T)', hol.SyntaxElementKind.TERM, None, 'exit'),
      ]),
      ('(v (bool) x)', hol.SyntaxElementKind.TERM, [
          ('(v (bool) x)', hol.SyntaxElementKind.TERM, None, 'enter'),
          ('v', hol.SyntaxElementKind.SEXPRESSION_KIND, 0, 'enter'),
          ('v', hol.SyntaxElementKind.SEXPRESSION_KIND, 0, 'exit'),
          ('(bool)', hol.SyntaxElementKind.TYPE, 1, 'enter'),
          ('bool', hol.SyntaxElementKind.TYPE_CONSTRUCTOR_NAME, 0, 'enter'),
          ('bool', hol.SyntaxElementKind.TYPE_CONSTRUCTOR_NAME, 0, 'exit'),
          ('(bool)', hol.SyntaxElementKind.TYPE, 1, 'exit'),
          ('x', hol.SyntaxElementKind.VARIABLE_NAME, 2, 'enter'),
          ('x', hol.SyntaxElementKind.VARIABLE_NAME, 2, 'exit'),
          ('(v (bool) x)', hol.SyntaxElementKind.TERM, None, 'exit'),
      ]),
      ('(l (v (bool) x) (v (bool) x))', hol.SyntaxElementKind.TERM, [
          ('(l (v (bool) x) (v (bool) x))', hol.SyntaxElementKind.TERM, None,
           'enter'),
          ('l', hol.SyntaxElementKind.SEXPRESSION_KIND, 0, 'enter'),
          ('l', hol.SyntaxElementKind.SEXPRESSION_KIND, 0, 'exit'),
          ('(v (bool) x)', hol.SyntaxElementKind.TERM, 1, 'enter'),
          ('v', hol.SyntaxElementKind.SEXPRESSION_KIND, 0, 'enter'),
          ('v', hol.SyntaxElementKind.SEXPRESSION_KIND, 0, 'exit'),
          ('(bool)', hol.SyntaxElementKind.TYPE, 1, 'enter'),
          ('bool', hol.SyntaxElementKind.TYPE_CONSTRUCTOR_NAME, 0, 'enter'),
          ('bool', hol.SyntaxElementKind.TYPE_CONSTRUCTOR_NAME, 0, 'exit'),
          ('x', hol.SyntaxElementKind.VARIABLE_NAME, 2, 'enter'),
          ('x', hol.SyntaxElementKind.VARIABLE_NAME, 2, 'exit'),
          ('(v (bool) x)', hol.SyntaxElementKind.TERM, 1, 'exit'),
          ('(v (bool) x)', hol.SyntaxElementKind.TERM, 2, 'enter'),
          ('v', hol.SyntaxElementKind.SEXPRESSION_KIND, 0, 'enter'),
          ('v', hol.SyntaxElementKind.SEXPRESSION_KIND, 0, 'exit'),
          ('(bool)', hol.SyntaxElementKind.TYPE, 1, 'enter'),
          ('bool', hol.SyntaxElementKind.TYPE_CONSTRUCTOR_NAME, 0, 'enter'),
          ('bool', hol.SyntaxElementKind.TYPE_CONSTRUCTOR_NAME, 0, 'exit'),
          ('(bool)', hol.SyntaxElementKind.TYPE, 1, 'exit'),
          ('x', hol.SyntaxElementKind.VARIABLE_NAME, 2, 'enter'),
          ('x', hol.SyntaxElementKind.VARIABLE_NAME, 2, 'exit'),
          ('(v (bool) x)', hol.SyntaxElementKind.TERM, 2, 'exit'),
          ('(l (v (bool) x) (v (bool) x))', hol.SyntaxElementKind.TERM, None,
           'exit'),
      ]),
      ('(a (v (fun (bool) (bool)) x) (v (bool) y))', hol.SyntaxElementKind.TERM,
       [
           ('(a (v (fun (bool) (bool)) x) (v (bool) y))',
            hol.SyntaxElementKind.TERM, None, 'enter'),
           ('a', hol.SyntaxElementKind.SEXPRESSION_KIND, 0, 'enter'),
           ('a', hol.SyntaxElementKind.SEXPRESSION_KIND, 0, 'exit'),
           ('(v (fun (bool) (bool)) x)', hol.SyntaxElementKind.TERM, 1,
            'enter'),
           ('v', hol.SyntaxElementKind.SEXPRESSION_KIND, 0, 'enter'),
           ('v', hol.SyntaxElementKind.SEXPRESSION_KIND, 0, 'exit'),
           ('(fun (bool) (bool))', hol.SyntaxElementKind.TYPE, 1, 'enter'),
           ('fun', hol.SyntaxElementKind.TYPE_CONSTRUCTOR_NAME, 0, 'enter'),
           ('fun', hol.SyntaxElementKind.TYPE_CONSTRUCTOR_NAME, 0, 'exit'),
           ('(bool)', hol.SyntaxElementKind.TYPE, 1, 'enter'),
           ('bool', hol.SyntaxElementKind.TYPE_CONSTRUCTOR_NAME, 0, 'enter'),
           ('bool', hol.SyntaxElementKind.TYPE_CONSTRUCTOR_NAME, 0, 'exit'),
           ('(bool)', hol.SyntaxElementKind.TYPE, 1, 'exit'),
           ('(bool)', hol.SyntaxElementKind.TYPE, 2, 'enter'),
           ('bool', hol.SyntaxElementKind.TYPE_CONSTRUCTOR_NAME, 0, 'enter'),
           ('bool', hol.SyntaxElementKind.TYPE_CONSTRUCTOR_NAME, 0, 'exit'),
           ('(bool)', hol.SyntaxElementKind.TYPE, 2, 'exit'),
           ('(fun (bool) (bool))', hol.SyntaxElementKind.TYPE, 1, 'exit'),
           ('x', hol.SyntaxElementKind.VARIABLE_NAME, 2, 'enter'),
           ('x', hol.SyntaxElementKind.VARIABLE_NAME, 2, 'exit'),
           ('(v (fun (bool) (bool)) x)', hol.SyntaxElementKind.TERM, 1, 'exit'),
           ('(v (bool) y)', hol.SyntaxElementKind.TERM, 2, 'enter'),
           ('v', hol.SyntaxElementKind.SEXPRESSION_KIND, 0, 'enter'),
           ('v', hol.SyntaxElementKind.SEXPRESSION_KIND, 0, 'exit'),
           ('(bool)', hol.SyntaxElementKind.TYPE, 1, 'enter'),
           ('bool', hol.SyntaxElementKind.TYPE_CONSTRUCTOR_NAME, 0, 'enter'),
           ('bool', hol.SyntaxElementKind.TYPE_CONSTRUCTOR_NAME, 0, 'exit'),
           ('(bool)', hol.SyntaxElementKind.TYPE, 1, 'exit'),
           ('y', hol.SyntaxElementKind.VARIABLE_NAME, 2, 'enter'),
           ('y', hol.SyntaxElementKind.VARIABLE_NAME, 2, 'exit'),
           ('(v (bool) y)', hol.SyntaxElementKind.TERM, 2, 'exit'),
           ('(a (v (fun (bool) (bool)) x) (v (bool) y))',
            hol.SyntaxElementKind.TERM, None, 'exit'),
       ]),
      ('(c (bool) T)', hol.SyntaxElementKind.UNKNOWN, [
          ('(c (bool) T)', hol.SyntaxElementKind.UNKNOWN, None, 'enter'),
          ('c', hol.SyntaxElementKind.SEXPRESSION_KIND, 0, 'enter'),
          ('c', hol.SyntaxElementKind.SEXPRESSION_KIND, 0, 'exit'),
          ('(bool)', hol.SyntaxElementKind.TYPE, 1, 'enter'),
          ('bool', hol.SyntaxElementKind.TYPE_CONSTRUCTOR_NAME, 0, 'enter'),
          ('bool', hol.SyntaxElementKind.TYPE_CONSTRUCTOR_NAME, 0, 'exit'),
          ('(bool)', hol.SyntaxElementKind.TYPE, 1, 'exit'),
          ('T', hol.SyntaxElementKind.CONSTANT_NAME, 2, 'enter'),
          ('T', hol.SyntaxElementKind.CONSTANT_NAME, 2, 'exit'),
          ('(c (bool) T)', hol.SyntaxElementKind.UNKNOWN, None, 'exit'),
      ]),
      ('(v (bool) x)', hol.SyntaxElementKind.UNKNOWN, [
          ('(v (bool) x)', hol.SyntaxElementKind.UNKNOWN, None, 'enter'),
          ('v', hol.SyntaxElementKind.SEXPRESSION_KIND, 0, 'enter'),
          ('v', hol.SyntaxElementKind.SEXPRESSION_KIND, 0, 'exit'),
          ('(bool)', hol.SyntaxElementKind.TYPE, 1, 'enter'),
          ('bool', hol.SyntaxElementKind.TYPE_CONSTRUCTOR_NAME, 0, 'enter'),
          ('bool', hol.SyntaxElementKind.TYPE_CONSTRUCTOR_NAME, 0, 'exit'),
          ('(bool)', hol.SyntaxElementKind.TYPE, 1, 'exit'),
          ('x', hol.SyntaxElementKind.VARIABLE_NAME, 2, 'enter'),
          ('x', hol.SyntaxElementKind.VARIABLE_NAME, 2, 'exit'),
          ('(v (bool) x)', hol.SyntaxElementKind.UNKNOWN, None, 'exit'),
      ]),
      ('(l (v (bool) x) (v (bool) x))', hol.SyntaxElementKind.UNKNOWN, [
          ('(l (v (bool) x) (v (bool) x))', hol.SyntaxElementKind.UNKNOWN, None,
           'enter'),
          ('l', hol.SyntaxElementKind.SEXPRESSION_KIND, 0, 'enter'),
          ('l', hol.SyntaxElementKind.SEXPRESSION_KIND, 0, 'exit'),
          ('(v (bool) x)', hol.SyntaxElementKind.TERM, 1, 'enter'),
          ('v', hol.SyntaxElementKind.SEXPRESSION_KIND, 0, 'enter'),
          ('v', hol.SyntaxElementKind.SEXPRESSION_KIND, 0, 'exit'),
          ('(bool)', hol.SyntaxElementKind.TYPE, 1, 'enter'),
          ('bool', hol.SyntaxElementKind.TYPE_CONSTRUCTOR_NAME, 0, 'enter'),
          ('bool', hol.SyntaxElementKind.TYPE_CONSTRUCTOR_NAME, 0, 'exit'),
          ('x', hol.SyntaxElementKind.VARIABLE_NAME, 2, 'enter'),
          ('x', hol.SyntaxElementKind.VARIABLE_NAME, 2, 'exit'),
          ('(v (bool) x)', hol.SyntaxElementKind.TERM, 1, 'exit'),
          ('(v (bool) x)', hol.SyntaxElementKind.TERM, 2, 'enter'),
          ('v', hol.SyntaxElementKind.SEXPRESSION_KIND, 0, 'enter'),
          ('v', hol.SyntaxElementKind.SEXPRESSION_KIND, 0, 'exit'),
          ('(bool)', hol.SyntaxElementKind.TYPE, 1, 'enter'),
          ('bool', hol.SyntaxElementKind.TYPE_CONSTRUCTOR_NAME, 0, 'enter'),
          ('bool', hol.SyntaxElementKind.TYPE_CONSTRUCTOR_NAME, 0, 'exit'),
          ('(bool)', hol.SyntaxElementKind.TYPE, 1, 'exit'),
          ('x', hol.SyntaxElementKind.VARIABLE_NAME, 2, 'enter'),
          ('x', hol.SyntaxElementKind.VARIABLE_NAME, 2, 'exit'),
          ('(v (bool) x)', hol.SyntaxElementKind.TERM, 2, 'exit'),
          ('(l (v (bool) x) (v (bool) x))', hol.SyntaxElementKind.UNKNOWN, None,
           'exit'),
      ]),
      ('(a (v (fun (bool) (bool)) x) (v (bool) y))',
       hol.SyntaxElementKind.UNKNOWN, [
           ('(a (v (fun (bool) (bool)) x) (v (bool) y))',
            hol.SyntaxElementKind.UNKNOWN, None, 'enter'),
           ('a', hol.SyntaxElementKind.SEXPRESSION_KIND, 0, 'enter'),
           ('a', hol.SyntaxElementKind.SEXPRESSION_KIND, 0, 'exit'),
           ('(v (fun (bool) (bool)) x)', hol.SyntaxElementKind.TERM, 1,
            'enter'),
           ('v', hol.SyntaxElementKind.SEXPRESSION_KIND, 0, 'enter'),
           ('v', hol.SyntaxElementKind.SEXPRESSION_KIND, 0, 'exit'),
           ('(fun (bool) (bool))', hol.SyntaxElementKind.TYPE, 1, 'enter'),
           ('fun', hol.SyntaxElementKind.TYPE_CONSTRUCTOR_NAME, 0, 'enter'),
           ('fun', hol.SyntaxElementKind.TYPE_CONSTRUCTOR_NAME, 0, 'exit'),
           ('(bool)', hol.SyntaxElementKind.TYPE, 1, 'enter'),
           ('bool', hol.SyntaxElementKind.TYPE_CONSTRUCTOR_NAME, 0, 'enter'),
           ('bool', hol.SyntaxElementKind.TYPE_CONSTRUCTOR_NAME, 0, 'exit'),
           ('(bool)', hol.SyntaxElementKind.TYPE, 1, 'exit'),
           ('(bool)', hol.SyntaxElementKind.TYPE, 2, 'enter'),
           ('bool', hol.SyntaxElementKind.TYPE_CONSTRUCTOR_NAME, 0, 'enter'),
           ('bool', hol.SyntaxElementKind.TYPE_CONSTRUCTOR_NAME, 0, 'exit'),
           ('(bool)', hol.SyntaxElementKind.TYPE, 2, 'exit'),
           ('(fun (bool) (bool))', hol.SyntaxElementKind.TYPE, 1, 'exit'),
           ('x', hol.SyntaxElementKind.VARIABLE_NAME, 2, 'enter'),
           ('x', hol.SyntaxElementKind.VARIABLE_NAME, 2, 'exit'),
           ('(v (fun (bool) (bool)) x)', hol.SyntaxElementKind.TERM, 1, 'exit'),
           ('(v (bool) y)', hol.SyntaxElementKind.TERM, 2, 'enter'),
           ('v', hol.SyntaxElementKind.SEXPRESSION_KIND, 0, 'enter'),
           ('v', hol.SyntaxElementKind.SEXPRESSION_KIND, 0, 'exit'),
           ('(bool)', hol.SyntaxElementKind.TYPE, 1, 'enter'),
           ('bool', hol.SyntaxElementKind.TYPE_CONSTRUCTOR_NAME, 0, 'enter'),
           ('bool', hol.SyntaxElementKind.TYPE_CONSTRUCTOR_NAME, 0, 'exit'),
           ('(bool)', hol.SyntaxElementKind.TYPE, 1, 'exit'),
           ('y', hol.SyntaxElementKind.VARIABLE_NAME, 2, 'enter'),
           ('y', hol.SyntaxElementKind.VARIABLE_NAME, 2, 'exit'),
           ('(v (bool) y)', hol.SyntaxElementKind.TERM, 2, 'exit'),
           ('(a (v (fun (bool) (bool)) x) (v (bool) y))',
            hol.SyntaxElementKind.UNKNOWN, None, 'exit'),
       ]),
      ('(g () (v (bool) x))', hol.SyntaxElementKind.UNKNOWN, [
          ('(g () (v (bool) x))', hol.SyntaxElementKind.UNKNOWN, None, 'enter'),
          ('g', hol.SyntaxElementKind.UNKNOWN, 0, 'enter'),
          ('g', hol.SyntaxElementKind.UNKNOWN, 0, 'exit'),
          ('()', hol.SyntaxElementKind.UNKNOWN, 1, 'enter'),
          ('()', hol.SyntaxElementKind.UNKNOWN, 1, 'exit'),
          ('(v (bool) x)', hol.SyntaxElementKind.UNKNOWN, 2, 'enter'),
          ('v', hol.SyntaxElementKind.SEXPRESSION_KIND, 0, 'enter'),
          ('v', hol.SyntaxElementKind.SEXPRESSION_KIND, 0, 'exit'),
          ('(bool)', hol.SyntaxElementKind.TYPE, 1, 'enter'),
          ('bool', hol.SyntaxElementKind.TYPE_CONSTRUCTOR_NAME, 0, 'enter'),
          ('bool', hol.SyntaxElementKind.TYPE_CONSTRUCTOR_NAME, 0, 'exit'),
          ('(bool)', hol.SyntaxElementKind.TYPE, 1, 'exit'),
          ('x', hol.SyntaxElementKind.VARIABLE_NAME, 2, 'enter'),
          ('x', hol.SyntaxElementKind.VARIABLE_NAME, 2, 'exit'),
          ('(v (bool) x)', hol.SyntaxElementKind.UNKNOWN, 2, 'exit'),
          ('(g () (v (bool) x))', hol.SyntaxElementKind.UNKNOWN, None, 'exit'),
      ]),
  )
  def test_traverse_depth_first(self, sexp, node_kind, expected_result):
    traversal_log = []

    def _enter_fn(node, node_kind, index_in_parent):
      traversal_log.append((repr(node), node_kind, index_in_parent, 'enter'))

    def _exit_fn(node, node_kind, index_in_parent):
      traversal_log.append((repr(node), node_kind, index_in_parent, 'exit'))

    sexp_tree = sexpression_parser.to_tree(sexp)
    hol_light_tree = hol_light_sexpression_trees.HolLightSExpressionTree(
        sexp_tree, node_kind, has_type_atoms=False)
    hol_light_tree.traverse_depth_first(_enter_fn, _exit_fn)
    self.assertEqual(frozenset(expected_result), frozenset(traversal_log))

  @parameterized.parameters(
      ('A', hol.SyntaxElementKind.TYPE, [
          ('A', hol.SyntaxElementKind.TYPE, None, 'enter'),
          ('A', hol.SyntaxElementKind.TYPE, None, 'exit')
      ]),
      ('(<TYPE> bool)', hol.SyntaxElementKind.TYPE, [
          ('(<TYPE> bool)', hol.SyntaxElementKind.TYPE, None, 'enter'),
          ('<TYPE>', hol.SyntaxElementKind.TYPE_ATOM, 0, 'enter'),
          ('<TYPE>', hol.SyntaxElementKind.TYPE_ATOM, 0, 'exit'),
          ('bool', hol.SyntaxElementKind.TYPE_CONSTRUCTOR_NAME, 1, 'enter'),
          ('bool', hol.SyntaxElementKind.TYPE_CONSTRUCTOR_NAME, 1, 'exit'),
          ('(<TYPE> bool)', hol.SyntaxElementKind.TYPE, None, 'exit'),
      ]),
      ('(<TYPE> fun x y)', hol.SyntaxElementKind.TYPE, [
          ('(<TYPE> fun x y)', hol.SyntaxElementKind.TYPE, None, 'enter'),
          ('<TYPE>', hol.SyntaxElementKind.TYPE_ATOM, 0, 'enter'),
          ('<TYPE>', hol.SyntaxElementKind.TYPE_ATOM, 0, 'exit'),
          ('fun', hol.SyntaxElementKind.TYPE_CONSTRUCTOR_NAME, 1, 'enter'),
          ('fun', hol.SyntaxElementKind.TYPE_CONSTRUCTOR_NAME, 1, 'exit'),
          ('x', hol.SyntaxElementKind.TYPE, 2, 'enter'),
          ('x', hol.SyntaxElementKind.TYPE, 2, 'exit'),
          ('y', hol.SyntaxElementKind.TYPE, 3, 'enter'),
          ('y', hol.SyntaxElementKind.TYPE, 3, 'exit'),
          ('(<TYPE> fun x y)', hol.SyntaxElementKind.TYPE, None, 'exit'),
      ]),
      ('(c (<TYPE> bool) T)', hol.SyntaxElementKind.TERM, [
          ('(c (<TYPE> bool) T)', hol.SyntaxElementKind.TERM, None, 'enter'),
          ('c', hol.SyntaxElementKind.SEXPRESSION_KIND, 0, 'enter'),
          ('c', hol.SyntaxElementKind.SEXPRESSION_KIND, 0, 'exit'),
          ('(<TYPE> bool)', hol.SyntaxElementKind.TYPE, 1, 'enter'),
          ('<TYPE>', hol.SyntaxElementKind.TYPE_ATOM, 0, 'enter'),
          ('<TYPE>', hol.SyntaxElementKind.TYPE_ATOM, 0, 'exit'),
          ('bool', hol.SyntaxElementKind.TYPE_CONSTRUCTOR_NAME, 1, 'enter'),
          ('bool', hol.SyntaxElementKind.TYPE_CONSTRUCTOR_NAME, 1, 'exit'),
          ('(<TYPE> bool)', hol.SyntaxElementKind.TYPE, 1, 'exit'),
          ('T', hol.SyntaxElementKind.CONSTANT_NAME, 2, 'enter'),
          ('T', hol.SyntaxElementKind.CONSTANT_NAME, 2, 'exit'),
          ('(c (<TYPE> bool) T)', hol.SyntaxElementKind.TERM, None, 'exit'),
      ]),
      ('(v (<TYPE> bool) x)', hol.SyntaxElementKind.TERM, [
          ('(v (<TYPE> bool) x)', hol.SyntaxElementKind.TERM, None, 'enter'),
          ('v', hol.SyntaxElementKind.SEXPRESSION_KIND, 0, 'enter'),
          ('v', hol.SyntaxElementKind.SEXPRESSION_KIND, 0, 'exit'),
          ('(<TYPE> bool)', hol.SyntaxElementKind.TYPE, 1, 'enter'),
          ('<TYPE>', hol.SyntaxElementKind.TYPE_ATOM, 0, 'enter'),
          ('<TYPE>', hol.SyntaxElementKind.TYPE_ATOM, 0, 'exit'),
          ('bool', hol.SyntaxElementKind.TYPE_CONSTRUCTOR_NAME, 1, 'enter'),
          ('bool', hol.SyntaxElementKind.TYPE_CONSTRUCTOR_NAME, 1, 'exit'),
          ('(<TYPE> bool)', hol.SyntaxElementKind.TYPE, 1, 'exit'),
          ('x', hol.SyntaxElementKind.VARIABLE_NAME, 2, 'enter'),
          ('x', hol.SyntaxElementKind.VARIABLE_NAME, 2, 'exit'),
          ('(v (<TYPE> bool) x)', hol.SyntaxElementKind.TERM, None, 'exit'),
      ]),
      ('(l (v (<TYPE> bool) x) (v (<TYPE> bool) x))',
       hol.SyntaxElementKind.TERM, [
           ('(l (v (<TYPE> bool) x) (v (<TYPE> bool) x))',
            hol.SyntaxElementKind.TERM, None, 'enter'),
           ('l', hol.SyntaxElementKind.SEXPRESSION_KIND, 0, 'enter'),
           ('l', hol.SyntaxElementKind.SEXPRESSION_KIND, 0, 'exit'),
           ('(v (<TYPE> bool) x)', hol.SyntaxElementKind.TERM, 1, 'enter'),
           ('v', hol.SyntaxElementKind.SEXPRESSION_KIND, 0, 'enter'),
           ('v', hol.SyntaxElementKind.SEXPRESSION_KIND, 0, 'exit'),
           ('(<TYPE> bool)', hol.SyntaxElementKind.TYPE, 1, 'enter'),
           ('<TYPE>', hol.SyntaxElementKind.TYPE_ATOM, 0, 'enter'),
           ('<TYPE>', hol.SyntaxElementKind.TYPE_ATOM, 0, 'exit'),
           ('bool', hol.SyntaxElementKind.TYPE_CONSTRUCTOR_NAME, 1, 'enter'),
           ('bool', hol.SyntaxElementKind.TYPE_CONSTRUCTOR_NAME, 1, 'exit'),
           ('x', hol.SyntaxElementKind.VARIABLE_NAME, 2, 'enter'),
           ('x', hol.SyntaxElementKind.VARIABLE_NAME, 2, 'exit'),
           ('(v (<TYPE> bool) x)', hol.SyntaxElementKind.TERM, 1, 'exit'),
           ('(v (<TYPE> bool) x)', hol.SyntaxElementKind.TERM, 2, 'enter'),
           ('v', hol.SyntaxElementKind.SEXPRESSION_KIND, 0, 'enter'),
           ('v', hol.SyntaxElementKind.SEXPRESSION_KIND, 0, 'exit'),
           ('(<TYPE> bool)', hol.SyntaxElementKind.TYPE, 1, 'enter'),
           ('<TYPE>', hol.SyntaxElementKind.TYPE_ATOM, 0, 'enter'),
           ('<TYPE>', hol.SyntaxElementKind.TYPE_ATOM, 0, 'exit'),
           ('bool', hol.SyntaxElementKind.TYPE_CONSTRUCTOR_NAME, 1, 'enter'),
           ('bool', hol.SyntaxElementKind.TYPE_CONSTRUCTOR_NAME, 1, 'exit'),
           ('(<TYPE> bool)', hol.SyntaxElementKind.TYPE, 1, 'exit'),
           ('x', hol.SyntaxElementKind.VARIABLE_NAME, 2, 'enter'),
           ('x', hol.SyntaxElementKind.VARIABLE_NAME, 2, 'exit'),
           ('(v (<TYPE> bool) x)', hol.SyntaxElementKind.TERM, 2, 'exit'),
           ('(l (v (<TYPE> bool) x) (v (<TYPE> bool) x))',
            hol.SyntaxElementKind.TERM, None, 'exit'),
       ]),
      ('(a (v (<TYPE> fun (<TYPE> bool) (<TYPE> bool)) x) (v (<TYPE> bool) y))',
       hol.SyntaxElementKind.TERM, [
           ('(a (v (<TYPE> fun (<TYPE> bool) (<TYPE> bool)) x) (v (<TYPE> bool) y))',
            hol.SyntaxElementKind.TERM, None, 'enter'),
           ('a', hol.SyntaxElementKind.SEXPRESSION_KIND, 0, 'enter'),
           ('a', hol.SyntaxElementKind.SEXPRESSION_KIND, 0, 'exit'),
           ('(v (<TYPE> fun (<TYPE> bool) (<TYPE> bool)) x)',
            hol.SyntaxElementKind.TERM, 1, 'enter'),
           ('v', hol.SyntaxElementKind.SEXPRESSION_KIND, 0, 'enter'),
           ('v', hol.SyntaxElementKind.SEXPRESSION_KIND, 0, 'exit'),
           ('(<TYPE> fun (<TYPE> bool) (<TYPE> bool))',
            hol.SyntaxElementKind.TYPE, 1, 'enter'),
           ('<TYPE>', hol.SyntaxElementKind.TYPE_ATOM, 0, 'enter'),
           ('<TYPE>', hol.SyntaxElementKind.TYPE_ATOM, 0, 'exit'),
           ('fun', hol.SyntaxElementKind.TYPE_CONSTRUCTOR_NAME, 1, 'enter'),
           ('fun', hol.SyntaxElementKind.TYPE_CONSTRUCTOR_NAME, 1, 'exit'),
           ('(<TYPE> bool)', hol.SyntaxElementKind.TYPE, 2, 'enter'),
           ('<TYPE>', hol.SyntaxElementKind.TYPE_ATOM, 0, 'enter'),
           ('<TYPE>', hol.SyntaxElementKind.TYPE_ATOM, 0, 'exit'),
           ('bool', hol.SyntaxElementKind.TYPE_CONSTRUCTOR_NAME, 1, 'enter'),
           ('bool', hol.SyntaxElementKind.TYPE_CONSTRUCTOR_NAME, 1, 'exit'),
           ('(<TYPE> bool)', hol.SyntaxElementKind.TYPE, 2, 'exit'),
           ('(<TYPE> bool)', hol.SyntaxElementKind.TYPE, 3, 'enter'),
           ('<TYPE>', hol.SyntaxElementKind.TYPE_ATOM, 0, 'enter'),
           ('<TYPE>', hol.SyntaxElementKind.TYPE_ATOM, 0, 'exit'),
           ('bool', hol.SyntaxElementKind.TYPE_CONSTRUCTOR_NAME, 1, 'enter'),
           ('bool', hol.SyntaxElementKind.TYPE_CONSTRUCTOR_NAME, 1, 'exit'),
           ('(<TYPE> bool)', hol.SyntaxElementKind.TYPE, 3, 'exit'),
           ('(<TYPE> fun (<TYPE> bool) (<TYPE> bool))',
            hol.SyntaxElementKind.TYPE, 1, 'exit'),
           ('x', hol.SyntaxElementKind.VARIABLE_NAME, 2, 'enter'),
           ('x', hol.SyntaxElementKind.VARIABLE_NAME, 2, 'exit'),
           ('(v (<TYPE> fun (<TYPE> bool) (<TYPE> bool)) x)',
            hol.SyntaxElementKind.TERM, 1, 'exit'),
           ('(v (<TYPE> bool) y)', hol.SyntaxElementKind.TERM, 2, 'enter'),
           ('v', hol.SyntaxElementKind.SEXPRESSION_KIND, 0, 'enter'),
           ('v', hol.SyntaxElementKind.SEXPRESSION_KIND, 0, 'exit'),
           ('(<TYPE> bool)', hol.SyntaxElementKind.TYPE, 1, 'enter'),
           ('<TYPE>', hol.SyntaxElementKind.TYPE_ATOM, 0, 'enter'),
           ('<TYPE>', hol.SyntaxElementKind.TYPE_ATOM, 0, 'exit'),
           ('bool', hol.SyntaxElementKind.TYPE_CONSTRUCTOR_NAME, 1, 'enter'),
           ('bool', hol.SyntaxElementKind.TYPE_CONSTRUCTOR_NAME, 1, 'exit'),
           ('(<TYPE> bool)', hol.SyntaxElementKind.TYPE, 1, 'exit'),
           ('y', hol.SyntaxElementKind.VARIABLE_NAME, 2, 'enter'),
           ('y', hol.SyntaxElementKind.VARIABLE_NAME, 2, 'exit'),
           ('(v (<TYPE> bool) y)', hol.SyntaxElementKind.TERM, 2, 'exit'),
           ('(a (v (<TYPE> fun (<TYPE> bool) (<TYPE> bool)) x) (v (<TYPE> bool) y))',
            hol.SyntaxElementKind.TERM, None, 'exit'),
       ]),
      ('(c (<TYPE> bool) T)', hol.SyntaxElementKind.UNKNOWN, [
          ('(c (<TYPE> bool) T)', hol.SyntaxElementKind.UNKNOWN, None, 'enter'),
          ('c', hol.SyntaxElementKind.SEXPRESSION_KIND, 0, 'enter'),
          ('c', hol.SyntaxElementKind.SEXPRESSION_KIND, 0, 'exit'),
          ('(<TYPE> bool)', hol.SyntaxElementKind.TYPE, 1, 'enter'),
          ('<TYPE>', hol.SyntaxElementKind.TYPE_ATOM, 0, 'enter'),
          ('<TYPE>', hol.SyntaxElementKind.TYPE_ATOM, 0, 'exit'),
          ('bool', hol.SyntaxElementKind.TYPE_CONSTRUCTOR_NAME, 1, 'enter'),
          ('bool', hol.SyntaxElementKind.TYPE_CONSTRUCTOR_NAME, 1, 'exit'),
          ('(<TYPE> bool)', hol.SyntaxElementKind.TYPE, 1, 'exit'),
          ('T', hol.SyntaxElementKind.CONSTANT_NAME, 2, 'enter'),
          ('T', hol.SyntaxElementKind.CONSTANT_NAME, 2, 'exit'),
          ('(c (<TYPE> bool) T)', hol.SyntaxElementKind.UNKNOWN, None, 'exit'),
      ]),
      ('(v (<TYPE> bool) x)', hol.SyntaxElementKind.UNKNOWN, [
          ('(v (<TYPE> bool) x)', hol.SyntaxElementKind.UNKNOWN, None, 'enter'),
          ('v', hol.SyntaxElementKind.SEXPRESSION_KIND, 0, 'enter'),
          ('v', hol.SyntaxElementKind.SEXPRESSION_KIND, 0, 'exit'),
          ('(<TYPE> bool)', hol.SyntaxElementKind.TYPE, 1, 'enter'),
          ('<TYPE>', hol.SyntaxElementKind.TYPE_ATOM, 0, 'enter'),
          ('<TYPE>', hol.SyntaxElementKind.TYPE_ATOM, 0, 'exit'),
          ('bool', hol.SyntaxElementKind.TYPE_CONSTRUCTOR_NAME, 1, 'enter'),
          ('bool', hol.SyntaxElementKind.TYPE_CONSTRUCTOR_NAME, 1, 'exit'),
          ('(<TYPE> bool)', hol.SyntaxElementKind.TYPE, 1, 'exit'),
          ('x', hol.SyntaxElementKind.VARIABLE_NAME, 2, 'enter'),
          ('x', hol.SyntaxElementKind.VARIABLE_NAME, 2, 'exit'),
          ('(v (<TYPE> bool) x)', hol.SyntaxElementKind.UNKNOWN, None, 'exit'),
      ]),
      ('(l (v (<TYPE> bool) x) (v (<TYPE> bool) x))',
       hol.SyntaxElementKind.UNKNOWN, [
           ('(l (v (<TYPE> bool) x) (v (<TYPE> bool) x))',
            hol.SyntaxElementKind.UNKNOWN, None, 'enter'),
           ('l', hol.SyntaxElementKind.SEXPRESSION_KIND, 0, 'enter'),
           ('l', hol.SyntaxElementKind.SEXPRESSION_KIND, 0, 'exit'),
           ('(v (<TYPE> bool) x)', hol.SyntaxElementKind.TERM, 1, 'enter'),
           ('v', hol.SyntaxElementKind.SEXPRESSION_KIND, 0, 'enter'),
           ('v', hol.SyntaxElementKind.SEXPRESSION_KIND, 0, 'exit'),
           ('(<TYPE> bool)', hol.SyntaxElementKind.TYPE, 1, 'enter'),
           ('<TYPE>', hol.SyntaxElementKind.TYPE_ATOM, 0, 'enter'),
           ('<TYPE>', hol.SyntaxElementKind.TYPE_ATOM, 0, 'exit'),
           ('bool', hol.SyntaxElementKind.TYPE_CONSTRUCTOR_NAME, 1, 'enter'),
           ('bool', hol.SyntaxElementKind.TYPE_CONSTRUCTOR_NAME, 1, 'exit'),
           ('x', hol.SyntaxElementKind.VARIABLE_NAME, 2, 'enter'),
           ('x', hol.SyntaxElementKind.VARIABLE_NAME, 2, 'exit'),
           ('(v (<TYPE> bool) x)', hol.SyntaxElementKind.TERM, 1, 'exit'),
           ('(v (<TYPE> bool) x)', hol.SyntaxElementKind.TERM, 2, 'enter'),
           ('v', hol.SyntaxElementKind.SEXPRESSION_KIND, 0, 'enter'),
           ('v', hol.SyntaxElementKind.SEXPRESSION_KIND, 0, 'exit'),
           ('(<TYPE> bool)', hol.SyntaxElementKind.TYPE, 1, 'enter'),
           ('<TYPE>', hol.SyntaxElementKind.TYPE_ATOM, 0, 'enter'),
           ('<TYPE>', hol.SyntaxElementKind.TYPE_ATOM, 0, 'exit'),
           ('bool', hol.SyntaxElementKind.TYPE_CONSTRUCTOR_NAME, 1, 'enter'),
           ('bool', hol.SyntaxElementKind.TYPE_CONSTRUCTOR_NAME, 1, 'exit'),
           ('(<TYPE> bool)', hol.SyntaxElementKind.TYPE, 1, 'exit'),
           ('x', hol.SyntaxElementKind.VARIABLE_NAME, 2, 'enter'),
           ('x', hol.SyntaxElementKind.VARIABLE_NAME, 2, 'exit'),
           ('(v (<TYPE> bool) x)', hol.SyntaxElementKind.TERM, 2, 'exit'),
           ('(l (v (<TYPE> bool) x) (v (<TYPE> bool) x))',
            hol.SyntaxElementKind.UNKNOWN, None, 'exit'),
       ]),
      ('(a (v (<TYPE> fun (<TYPE> bool) (<TYPE> bool)) x) (v (<TYPE> bool) y))',
       hol.SyntaxElementKind.UNKNOWN, [
           ('(a (v (<TYPE> fun (<TYPE> bool) (<TYPE> bool)) x) (v (<TYPE> bool) y))',
            hol.SyntaxElementKind.UNKNOWN, None, 'enter'),
           ('a', hol.SyntaxElementKind.SEXPRESSION_KIND, 0, 'enter'),
           ('a', hol.SyntaxElementKind.SEXPRESSION_KIND, 0, 'exit'),
           ('(v (<TYPE> fun (<TYPE> bool) (<TYPE> bool)) x)',
            hol.SyntaxElementKind.TERM, 1, 'enter'),
           ('v', hol.SyntaxElementKind.SEXPRESSION_KIND, 0, 'enter'),
           ('v', hol.SyntaxElementKind.SEXPRESSION_KIND, 0, 'exit'),
           ('(<TYPE> fun (<TYPE> bool) (<TYPE> bool))',
            hol.SyntaxElementKind.TYPE, 1, 'enter'),
           ('<TYPE>', hol.SyntaxElementKind.TYPE_ATOM, 0, 'enter'),
           ('<TYPE>', hol.SyntaxElementKind.TYPE_ATOM, 0, 'exit'),
           ('fun', hol.SyntaxElementKind.TYPE_CONSTRUCTOR_NAME, 1, 'enter'),
           ('fun', hol.SyntaxElementKind.TYPE_CONSTRUCTOR_NAME, 1, 'exit'),
           ('(<TYPE> bool)', hol.SyntaxElementKind.TYPE, 2, 'enter'),
           ('<TYPE>', hol.SyntaxElementKind.TYPE_ATOM, 0, 'enter'),
           ('<TYPE>', hol.SyntaxElementKind.TYPE_ATOM, 0, 'exit'),
           ('bool', hol.SyntaxElementKind.TYPE_CONSTRUCTOR_NAME, 1, 'enter'),
           ('bool', hol.SyntaxElementKind.TYPE_CONSTRUCTOR_NAME, 1, 'exit'),
           ('(<TYPE> bool)', hol.SyntaxElementKind.TYPE, 2, 'exit'),
           ('(<TYPE> bool)', hol.SyntaxElementKind.TYPE, 3, 'enter'),
           ('<TYPE>', hol.SyntaxElementKind.TYPE_ATOM, 0, 'enter'),
           ('<TYPE>', hol.SyntaxElementKind.TYPE_ATOM, 0, 'exit'),
           ('bool', hol.SyntaxElementKind.TYPE_CONSTRUCTOR_NAME, 1, 'enter'),
           ('bool', hol.SyntaxElementKind.TYPE_CONSTRUCTOR_NAME, 1, 'exit'),
           ('(<TYPE> bool)', hol.SyntaxElementKind.TYPE, 3, 'exit'),
           ('(<TYPE> fun (<TYPE> bool) (<TYPE> bool))',
            hol.SyntaxElementKind.TYPE, 1, 'exit'),
           ('x', hol.SyntaxElementKind.VARIABLE_NAME, 2, 'enter'),
           ('x', hol.SyntaxElementKind.VARIABLE_NAME, 2, 'exit'),
           ('(v (<TYPE> fun (<TYPE> bool) (<TYPE> bool)) x)',
            hol.SyntaxElementKind.TERM, 1, 'exit'),
           ('(v (<TYPE> bool) y)', hol.SyntaxElementKind.TERM, 2, 'enter'),
           ('v', hol.SyntaxElementKind.SEXPRESSION_KIND, 0, 'enter'),
           ('v', hol.SyntaxElementKind.SEXPRESSION_KIND, 0, 'exit'),
           ('(<TYPE> bool)', hol.SyntaxElementKind.TYPE, 1, 'enter'),
           ('<TYPE>', hol.SyntaxElementKind.TYPE_ATOM, 0, 'enter'),
           ('<TYPE>', hol.SyntaxElementKind.TYPE_ATOM, 0, 'exit'),
           ('bool', hol.SyntaxElementKind.TYPE_CONSTRUCTOR_NAME, 1, 'enter'),
           ('bool', hol.SyntaxElementKind.TYPE_CONSTRUCTOR_NAME, 1, 'exit'),
           ('(<TYPE> bool)', hol.SyntaxElementKind.TYPE, 1, 'exit'),
           ('y', hol.SyntaxElementKind.VARIABLE_NAME, 2, 'enter'),
           ('y', hol.SyntaxElementKind.VARIABLE_NAME, 2, 'exit'),
           ('(v (<TYPE> bool) y)', hol.SyntaxElementKind.TERM, 2, 'exit'),
           ('(a (v (<TYPE> fun (<TYPE> bool) (<TYPE> bool)) x) (v (<TYPE> bool) y))',
            hol.SyntaxElementKind.UNKNOWN, None, 'exit'),
       ]),
      ('(g () (v (<TYPE> bool) x))', hol.SyntaxElementKind.UNKNOWN, [
          ('(g () (v (<TYPE> bool) x))', hol.SyntaxElementKind.UNKNOWN, None,
           'enter'),
          ('g', hol.SyntaxElementKind.UNKNOWN, 0, 'enter'),
          ('g', hol.SyntaxElementKind.UNKNOWN, 0, 'exit'),
          ('()', hol.SyntaxElementKind.UNKNOWN, 1, 'enter'),
          ('()', hol.SyntaxElementKind.UNKNOWN, 1, 'exit'),
          ('(v (<TYPE> bool) x)', hol.SyntaxElementKind.UNKNOWN, 2, 'enter'),
          ('v', hol.SyntaxElementKind.SEXPRESSION_KIND, 0, 'enter'),
          ('v', hol.SyntaxElementKind.SEXPRESSION_KIND, 0, 'exit'),
          ('(<TYPE> bool)', hol.SyntaxElementKind.TYPE, 1, 'enter'),
          ('<TYPE>', hol.SyntaxElementKind.TYPE_ATOM, 0, 'enter'),
          ('<TYPE>', hol.SyntaxElementKind.TYPE_ATOM, 0, 'exit'),
          ('bool', hol.SyntaxElementKind.TYPE_CONSTRUCTOR_NAME, 1, 'enter'),
          ('bool', hol.SyntaxElementKind.TYPE_CONSTRUCTOR_NAME, 1, 'exit'),
          ('(<TYPE> bool)', hol.SyntaxElementKind.TYPE, 1, 'exit'),
          ('x', hol.SyntaxElementKind.VARIABLE_NAME, 2, 'enter'),
          ('x', hol.SyntaxElementKind.VARIABLE_NAME, 2, 'exit'),
          ('(v (<TYPE> bool) x)', hol.SyntaxElementKind.UNKNOWN, 2, 'exit'),
          ('(g () (v (<TYPE> bool) x))', hol.SyntaxElementKind.UNKNOWN, None,
           'exit'),
      ]),
  )
  def test_traverse_depth_first_with_type_atoms(self, sexp, node_kind,
                                                expected_result):
    traversal_log = []

    def _enter_fn(node, node_kind, index_in_parent):
      traversal_log.append((repr(node), node_kind, index_in_parent, 'enter'))

    def _exit_fn(node, node_kind, index_in_parent):
      traversal_log.append((repr(node), node_kind, index_in_parent, 'exit'))

    sexp_tree = sexpression_parser.to_tree(sexp)
    hol_light_tree = hol_light_sexpression_trees.HolLightSExpressionTree(
        sexp_tree, node_kind, has_type_atoms=True)
    hol_light_tree.traverse_depth_first(_enter_fn, _exit_fn)
    self.assertEqual(frozenset(expected_result), frozenset(traversal_log))


if __name__ == '__main__':
  tf.test.main()
